/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;





/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt {
  public static final String SERIALIZED_NAME_FIN_INSTN_ID = "FinInstnId";
  @JsonProperty(SERIALIZED_NAME_FIN_INSTN_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgtFinInstnId finInstnId;

  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt finInstnId(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgtFinInstnId finInstnId) {
    this.finInstnId = finInstnId;
    return this;
  }

  /**
   * Get finInstnId
   * @return finInstnId
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgtFinInstnId getFinInstnId() {
    return finInstnId;
  }

  public void setFinInstnId(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgtFinInstnId finInstnId) {
    this.finInstnId = finInstnId;
  }
}

