/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponseDocument
 */

public class CreditoResponseDocument {
  public static final String SERIALIZED_NAME_HEADER = "Header";
  @JsonProperty(SERIALIZED_NAME_HEADER)
  @Nonnull
  private CreditoResponseDocumentHeader header;

  public static final String SERIALIZED_NAME_FI_TO_F_I_PMT_STS_RPT = "FIToFIPmtStsRpt";
  @JsonProperty(SERIALIZED_NAME_FI_TO_F_I_PMT_STS_RPT)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRpt fiToFIPmtStsRpt;

  public CreditoResponseDocument() {
  }

  public CreditoResponseDocument header(@Nonnull CreditoResponseDocumentHeader header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * 
   * @return header
   */
  @Nonnull
  public CreditoResponseDocumentHeader getHeader() {
    return header;
  }

  public void setHeader(@Nonnull CreditoResponseDocumentHeader header) {
    this.header = header;
  }

  public CreditoResponseDocument fiToFIPmtStsRpt(@Nonnull CreditoResponseDocumentFIToFIPmtStsRpt fiToFIPmtStsRpt) {
    this.fiToFIPmtStsRpt = fiToFIPmtStsRpt;
    return this;
  }

  /**
   * Get fiToFIPmtStsRpt
   * 
   * @return fiToFIPmtStsRpt
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRpt getFiToFIPmtStsRpt() {
    return fiToFIPmtStsRpt;
  }

  public void setFiToFIPmtStsRpt(@Nonnull CreditoResponseDocumentFIToFIPmtStsRpt fiToFIPmtStsRpt) {
    this.fiToFIPmtStsRpt = fiToFIPmtStsRpt;
  }

}
