/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrCtctDtls
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrCtctDtls {
  public static final String SERIALIZED_NAME_ALIAS = "Alias";
  @JsonProperty(SERIALIZED_NAME_ALIAS)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String alias;

  public static final String SERIALIZED_NAME_VALUE = "Value";
  @JsonProperty(SERIALIZED_NAME_VALUE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String value;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrCtctDtls() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrCtctDtls alias(@Nonnull String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * 
   * @return alias
   */
  @Nonnull
  public String getAlias() {
    return alias;
  }

  public void setAlias(@Nonnull String alias) {
    this.alias = alias;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrCtctDtls value(@Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * 
   * @return value
   */
  @Nonnull
  public String getValue() {
    return value;
  }

  public void setValue(@Nonnull String value) {
    this.value = value;
  }
}
