/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;


import jakarta.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * CreditoResponseDocumentFIToFIPmtStsRptGrpHdrSttInf
 */

public class CreditoResponseDocumentFIToFIPmtStsRptGrpHdrSttInf {
  public static final String SERIALIZED_NAME_STTLM_MTD = "SttlmMtd";
  @JsonProperty(SERIALIZED_NAME_STTLM_MTD)
  @Nullable
  private String sttlmMtd;

  public CreditoResponseDocumentFIToFIPmtStsRptGrpHdrSttInf() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptGrpHdrSttInf sttlmMtd(@Nullable String sttlmMtd) {
    this.sttlmMtd = sttlmMtd;
    return this;
  }

  /**
   * Get sttlmMtd
   * @return sttlmMtd
   */
  @Nullable
  public String getSttlmMtd() {
    return sttlmMtd;
  }

  public void setSttlmMtd(@Nullable String sttlmMtd) {
    this.sttlmMtd = sttlmMtd;
  }
}

