/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;





/**
 * CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf
 */

public class CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf {
  public static final String SERIALIZED_NAME_ORGNL_MSG_ID = "OrgnlMsgId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_MSG_ID)
  @Nonnull
  private String orgnlMsgId;

  public static final String SERIALIZED_NAME_ORGNL_MSG_NM_ID = "OrgnlMsgNmId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_MSG_NM_ID)
  @Nonnull
  private String orgnlMsgNmId;

  public static final String SERIALIZED_NAME_ORGNL_CRE_DT_TM = "OrgnlCreDtTm";
  @JsonProperty(SERIALIZED_NAME_ORGNL_CRE_DT_TM)
  @Nonnull
  private String orgnlCreDtTm;

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlMsgId(@Nonnull String orgnlMsgId) {
    this.orgnlMsgId = orgnlMsgId;
    return this;
  }

  /**
   * Get orgnlMsgId
   * @return orgnlMsgId
   */
  @Nonnull
  public String getOrgnlMsgId() {
    return orgnlMsgId;
  }

  public void setOrgnlMsgId(@Nonnull String orgnlMsgId) {
    this.orgnlMsgId = orgnlMsgId;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlMsgNmId(@Nonnull String orgnlMsgNmId) {
    this.orgnlMsgNmId = orgnlMsgNmId;
    return this;
  }

  /**
   * Get orgnlMsgNmId
   * @return orgnlMsgNmId
   */
  @Nonnull
  public String getOrgnlMsgNmId() {
    return orgnlMsgNmId;
  }

  public void setOrgnlMsgNmId(@Nonnull String orgnlMsgNmId) {
    this.orgnlMsgNmId = orgnlMsgNmId;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlCreDtTm(@Nonnull String orgnlCreDtTm) {
    this.orgnlCreDtTm = orgnlCreDtTm;
    return this;
  }

  /**
   * Get orgnlCreDtTm
   * @return orgnlCreDtTm
   */
  @Nonnull
  public String getOrgnlCreDtTm() {
    return orgnlCreDtTm;
  }

  public void setOrgnlCreDtTm(@Nonnull String orgnlCreDtTm) {
    this.orgnlCreDtTm = orgnlCreDtTm;
  }
}

