/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoRequestDocumentHeader
 */

public class CreditoRequestDocumentHeader {
  public static final String SERIALIZED_NAME_ORIG_ID = "OrigId";
  @JsonProperty(SERIALIZED_NAME_ORIG_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentHeaderOrigId origId;

  public static final String SERIALIZED_NAME_SENDER = "Sender";
  @JsonProperty(SERIALIZED_NAME_SENDER)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String sender;

  public static final String SERIALIZED_NAME_RECEIVER = "Receiver";
  @JsonProperty(SERIALIZED_NAME_RECEIVER)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String receiver;

  public static final String SERIALIZED_NAME_MGE = "Mge";
  @JsonProperty(SERIALIZED_NAME_MGE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentHeaderMge mge;

  public static final String SERIALIZED_NAME_PSSBL_DPLCT = "PssblDplct";
  @JsonProperty(SERIALIZED_NAME_PSSBL_DPLCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String pssblDplct;

  public static final String SERIALIZED_NAME_PRTY = "Prty";
  @JsonProperty(SERIALIZED_NAME_PRTY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String prty;

  public CreditoRequestDocumentHeader() {
  }

  public CreditoRequestDocumentHeader origId(@Nonnull CreditoRequestDocumentHeaderOrigId origId) {
    this.origId = origId;
    return this;
  }

  /**
   * Get origId
   * 
   * @return origId
   */
  @Nonnull
  public CreditoRequestDocumentHeaderOrigId getOrigId() {
    return origId;
  }

  public void setOrigId(@Nonnull CreditoRequestDocumentHeaderOrigId origId) {
    this.origId = origId;
  }

  public CreditoRequestDocumentHeader sender(@Nonnull String sender) {
    this.sender = sender;
    return this;
  }

  /**
   * Get sender
   * 
   * @return sender
   */
  @Nonnull
  public String getSender() {
    return sender;
  }

  public void setSender(@Nonnull String sender) {
    this.sender = sender;
  }

  public CreditoRequestDocumentHeader receiver(@Nonnull String receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * Get receiver
   * 
   * @return receiver
   */
  @Nonnull
  public String getReceiver() {
    return receiver;
  }

  public void setReceiver(@Nonnull String receiver) {
    this.receiver = receiver;
  }

  public CreditoRequestDocumentHeader mge(@Nonnull CreditoRequestDocumentHeaderMge mge) {
    this.mge = mge;
    return this;
  }

  /**
   * Get mge
   * 
   * @return mge
   */
  @Nonnull
  public CreditoRequestDocumentHeaderMge getMge() {
    return mge;
  }

  public void setMge(@Nonnull CreditoRequestDocumentHeaderMge mge) {
    this.mge = mge;
  }

  public CreditoRequestDocumentHeader pssblDplct(@Nonnull String pssblDplct) {
    this.pssblDplct = pssblDplct;
    return this;
  }

  /**
   * Get pssblDplct
   * 
   * @return pssblDplct
   */
  @Nonnull
  public String getPssblDplct() {
    return pssblDplct;
  }

  public void setPssblDplct(@Nonnull String pssblDplct) {
    this.pssblDplct = pssblDplct;
  }

  public CreditoRequestDocumentHeader prty(@Nonnull String prty) {
    this.prty = prty;
    return this;
  }

  /**
   * Get prty
   * 
   * @return prty
   */
  @Nonnull
  public String getPrty() {
    return prty;
  }

  public void setPrty(@Nonnull String prty) {
    this.prty = prty;
  }
}
