/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgtFinInstnIdOthr
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgtFinInstnIdOthr {
  public static final String SERIALIZED_NAME_ID = "Id";
  @JsonProperty(SERIALIZED_NAME_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String id;

  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgtFinInstnIdOthr() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgtFinInstnIdOthr id(@Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * 
   * @return id
   */
  @Nonnull
  public String getId() {
    return id;
  }

  public void setId(@Nonnull String id) {
    this.id = id;
  }
}
