/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr {
  public static final String SERIALIZED_NAME_CTCT_DTLS = "CtctDtls";
  @JsonProperty(SERIALIZED_NAME_CTCT_DTLS)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrCtctDtls ctctDtls;

  public static final String SERIALIZED_NAME_NM = "Nm";
  @JsonProperty(SERIALIZED_NAME_NM)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String nm;

  public static final String SERIALIZED_NAME_ID = "Id";
  @JsonProperty(SERIALIZED_NAME_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId id;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr ctctDtls(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrCtctDtls ctctDtls) {
    this.ctctDtls = ctctDtls;
    return this;
  }

  /**
   * Get ctctDtls
   * 
   * @return ctctDtls
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrCtctDtls getCtctDtls() {
    return ctctDtls;
  }

  public void setCtctDtls(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrCtctDtls ctctDtls) {
    this.ctctDtls = ctctDtls;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr nm(@Nonnull String nm) {
    this.nm = nm;
    return this;
  }

  /**
   * Get nm
   * 
   * @return nm
   */
  @Nonnull
  public String getNm() {
    return nm;
  }

  public void setNm(@Nonnull String nm) {
    this.nm = nm;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr id(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * 
   * @return id
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId getId() {
    return id;
  }

  public void setId(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId id) {
    this.id = id;
  }
}
