/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonProperty;





/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrId
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrId {
  public static final String SERIALIZED_NAME_PRVT_ID = "PrvtId";
  @JsonProperty(SERIALIZED_NAME_PRVT_ID)
  @Nullable
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrIdPrvtId prvtId;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrId() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrId prvtId(@Nullable CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
    return this;
  }

  /**
   * Get prvtId
   * @return prvtId
   */
  @Nullable
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrIdPrvtId getPrvtId() {
    return prvtId;
  }

  public void setPrvtId(@Nullable CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
  }
}

