/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf {
  public static final String SERIALIZED_NAME_PMT_ID = "PmtId";
  @JsonProperty(SERIALIZED_NAME_PMT_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtId pmtId;

  public static final String SERIALIZED_NAME_PMT_TP_INF = "PmtTpInf";
  @JsonProperty(SERIALIZED_NAME_PMT_TP_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf pmtTpInf;

  public static final String SERIALIZED_NAME_INTR_BK_STTLM_AMT = "IntrBkSttlmAmt";
  @JsonProperty(SERIALIZED_NAME_INTR_BK_STTLM_AMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intrBkSttlmAmt;

  public static final String SERIALIZED_NAME_INTR_BK_STTLM_AMT_CCY = "IntrBkSttlmAmtCcy";
  @JsonProperty(SERIALIZED_NAME_INTR_BK_STTLM_AMT_CCY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intrBkSttlmAmtCcy;

  public static final String SERIALIZED_NAME_INT_BK_STTLM_DT = "IntBkSttlmDt";
  @JsonProperty(SERIALIZED_NAME_INT_BK_STTLM_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intBkSttlmDt;

  public static final String SERIALIZED_NAME_CHRG_BR = "ChrgBr";
  @JsonProperty(SERIALIZED_NAME_CHRG_BR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private Object chrgBr;

  public static final String SERIALIZED_NAME_DBTR = "Dbtr";
  @JsonProperty(SERIALIZED_NAME_DBTR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtr dbtr;

  public static final String SERIALIZED_NAME_DBTR_ACCT = "DbtrAcct";
  @JsonProperty(SERIALIZED_NAME_DBTR_ACCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrAcct dbtrAcct;

  public static final String SERIALIZED_NAME_DBTR_AGT = "DbtrAgt";
  @JsonProperty(SERIALIZED_NAME_DBTR_AGT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt dbtrAgt;

  public static final String SERIALIZED_NAME_CDTR_AGT = "CdtrAgt";
  @JsonProperty(SERIALIZED_NAME_CDTR_AGT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgt cdtrAgt;

  public static final String SERIALIZED_NAME_CDTR = "Cdtr";
  @JsonProperty(SERIALIZED_NAME_CDTR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr cdtr;

  public static final String SERIALIZED_NAME_CDTR_ACCT = "CdtrAcct";
  @JsonProperty(SERIALIZED_NAME_CDTR_ACCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrAcct cdtrAcct;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryData splmtryData;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf pmtId(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtId pmtId) {
    this.pmtId = pmtId;
    return this;
  }

  /**
   * Get pmtId
   * 
   * @return pmtId
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtId getPmtId() {
    return pmtId;
  }

  public void setPmtId(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtId pmtId) {
    this.pmtId = pmtId;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf pmtTpInf(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf pmtTpInf) {
    this.pmtTpInf = pmtTpInf;
    return this;
  }

  /**
   * Get pmtTpInf
   * 
   * @return pmtTpInf
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf getPmtTpInf() {
    return pmtTpInf;
  }

  public void setPmtTpInf(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf pmtTpInf) {
    this.pmtTpInf = pmtTpInf;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf intrBkSttlmAmt(@Nonnull String intrBkSttlmAmt) {
    this.intrBkSttlmAmt = intrBkSttlmAmt;
    return this;
  }

  /**
   * Get intrBkSttlmAmt
   * 
   * @return intrBkSttlmAmt
   */
  @Nonnull
  public String getIntrBkSttlmAmt() {
    return intrBkSttlmAmt;
  }

  public void setIntrBkSttlmAmt(@Nonnull String intrBkSttlmAmt) {
    this.intrBkSttlmAmt = intrBkSttlmAmt;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf intrBkSttlmAmtCcy(@Nonnull String intrBkSttlmAmtCcy) {
    this.intrBkSttlmAmtCcy = intrBkSttlmAmtCcy;
    return this;
  }

  /**
   * Get intrBkSttlmAmtCcy
   * 
   * @return intrBkSttlmAmtCcy
   */
  @Nonnull
  public String getIntrBkSttlmAmtCcy() {
    return intrBkSttlmAmtCcy;
  }

  public void setIntrBkSttlmAmtCcy(@Nonnull String intrBkSttlmAmtCcy) {
    this.intrBkSttlmAmtCcy = intrBkSttlmAmtCcy;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf intBkSttlmDt(@Nonnull String intBkSttlmDt) {
    this.intBkSttlmDt = intBkSttlmDt;
    return this;
  }

  /**
   * Get intBkSttlmDt
   * 
   * @return intBkSttlmDt
   */
  @Nonnull
  public String getIntBkSttlmDt() {
    return intBkSttlmDt;
  }

  public void setIntBkSttlmDt(@Nonnull String intBkSttlmDt) {
    this.intBkSttlmDt = intBkSttlmDt;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf chrgBr(@Nonnull Object chrgBr) {
    this.chrgBr = chrgBr;
    return this;
  }

  /**
   * Get chrgBr
   * 
   * @return chrgBr
   */
  @Nonnull
  public Object getChrgBr() {
    return chrgBr;
  }

  public void setChrgBr(@Nonnull Object chrgBr) {
    this.chrgBr = chrgBr;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf dbtr(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtr dbtr) {
    this.dbtr = dbtr;
    return this;
  }

  /**
   * Get dbtr
   * 
   * @return dbtr
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtr getDbtr() {
    return dbtr;
  }

  public void setDbtr(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtr dbtr) {
    this.dbtr = dbtr;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf dbtrAcct(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrAcct dbtrAcct) {
    this.dbtrAcct = dbtrAcct;
    return this;
  }

  /**
   * Get dbtrAcct
   * 
   * @return dbtrAcct
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrAcct getDbtrAcct() {
    return dbtrAcct;
  }

  public void setDbtrAcct(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfDbtrAcct dbtrAcct) {
    this.dbtrAcct = dbtrAcct;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf dbtrAgt(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt dbtrAgt) {
    this.dbtrAgt = dbtrAgt;
    return this;
  }

  /**
   * Get dbtrAgt
   * 
   * @return dbtrAgt
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt getDbtrAgt() {
    return dbtrAgt;
  }

  public void setDbtrAgt(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstgAgt dbtrAgt) {
    this.dbtrAgt = dbtrAgt;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtrAgt(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgt cdtrAgt) {
    this.cdtrAgt = cdtrAgt;
    return this;
  }

  /**
   * Get cdtrAgt
   * 
   * @return cdtrAgt
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgt getCdtrAgt() {
    return cdtrAgt;
  }

  public void setCdtrAgt(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdrInstdAgt cdtrAgt) {
    this.cdtrAgt = cdtrAgt;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtr(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr cdtr) {
    this.cdtr = cdtr;
    return this;
  }

  /**
   * Get cdtr
   * 
   * @return cdtr
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr getCdtr() {
    return cdtr;
  }

  public void setCdtr(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtr cdtr) {
    this.cdtr = cdtr;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtrAcct(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrAcct cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
    return this;
  }

  /**
   * Get cdtrAcct
   * 
   * @return cdtrAcct
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrAcct getCdtrAcct() {
    return cdtrAcct;
  }

  public void setCdtrAcct(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrAcct cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf splmtryData(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * 
   * @return splmtryData
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }
}
