/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponseDocumentFIToFIPmtStsRpt
 */

public class CreditoResponseDocumentFIToFIPmtStsRpt {
  public static final String SERIALIZED_NAME_GRP_HDR = "GrpHdr";
  @JsonProperty(SERIALIZED_NAME_GRP_HDR)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptGrpHdr grpHdr;

  public static final String SERIALIZED_NAME_TX_INF_AND_STS = "TxInfAndSts";
  @JsonProperty(SERIALIZED_NAME_TX_INF_AND_STS)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts txInfAndSts;

  public CreditoResponseDocumentFIToFIPmtStsRpt() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRpt grpHdr(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
    return this;
  }

  /**
   * Get grpHdr
   * 
   * @return grpHdr
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptGrpHdr getGrpHdr() {
    return grpHdr;
  }

  public void setGrpHdr(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
  }

  public CreditoResponseDocumentFIToFIPmtStsRpt txInfAndSts(
      @Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
    return this;
  }

  /**
   * Get txInfAndSts
   * 
   * @return txInfAndSts
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts getTxInfAndSts() {
    return txInfAndSts;
  }

  public void setTxInfAndSts(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
  }

}
