/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData
 */

public class CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData {
  public static final String SERIALIZED_NAME_ENVLP = "Envlp";
  @JsonProperty(SERIALIZED_NAME_ENVLP)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp;

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData envlp(
      @Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
    return this;
  }

  /**
   * Get envlp
   * 
   * @return envlp
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp getEnvlp() {
    return envlp;
  }

  public void setEnvlp(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
  }

}
