/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts {
  public static final String SERIALIZED_NAME_CHAN_REF = "ChanRef";
  @JsonProperty(SERIALIZED_NAME_CHAN_REF)
  @Nullable
  private String chanRef;

  public static final String SERIALIZED_NAME_AGT_REF = "AgtRef";
  @JsonProperty(SERIALIZED_NAME_AGT_REF)
  @Nullable
  private String agtRef;

  public static final String SERIALIZED_NAME_DBT_CRED = "DbtCred";
  @JsonProperty(SERIALIZED_NAME_DBT_CRED)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String dbtCred;

  public static final String SERIALIZED_NAME_STTLM_DT = "SttlmDt";
  @JsonProperty(SERIALIZED_NAME_STTLM_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String sttlmDt;

  public static final String SERIALIZED_NAME_TRACK2 = "Track2";
  @JsonProperty(SERIALIZED_NAME_TRACK2)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String track2;

  public static final String SERIALIZED_NAME_ADITIONAL_DATA = "AditionalData";
  @JsonProperty(SERIALIZED_NAME_ADITIONAL_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String aditionalData;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts chanRef(@Nullable String chanRef) {
    this.chanRef = chanRef;
    return this;
  }

  /**
   * Get chanRef
   * @return chanRef
   */
  @Nullable
  public String getChanRef() {
    return chanRef;
  }

  public void setChanRef(@Nullable String chanRef) {
    this.chanRef = chanRef;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts agtRef(@Nullable String agtRef) {
    this.agtRef = agtRef;
    return this;
  }

  /**
   * Get agtRef
   * @return agtRef
   */
  @Nullable
  public String getAgtRef() {
    return agtRef;
  }

  public void setAgtRef(@Nullable String agtRef) {
    this.agtRef = agtRef;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts dbtCred(@Nonnull String dbtCred) {
    this.dbtCred = dbtCred;
    return this;
  }

  /**
   * Get dbtCred
   * @return dbtCred
   */
  @Nonnull
  public String getDbtCred() {
    return dbtCred;
  }

  public void setDbtCred(@Nonnull String dbtCred) {
    this.dbtCred = dbtCred;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts sttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
    return this;
  }

  /**
   * Get sttlmDt
   * @return sttlmDt
   */
  @Nonnull
  public String getSttlmDt() {
    return sttlmDt;
  }

  public void setSttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts track2(@Nonnull String track2) {
    this.track2 = track2;
    return this;
  }

  /**
   * Get track2
   * @return track2
   */
  @Nonnull
  public String getTrack2() {
    return track2;
  }

  public void setTrack2(@Nonnull String track2) {
    this.track2 = track2;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfSplmtryDataEnvlpCnts aditionalData(@Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
    return this;
  }

  /**
   * Get aditionalData
   * @return aditionalData
   */
  @Nonnull
  public String getAditionalData() {
    return aditionalData;
  }

  public void setAditionalData(@Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
  }
}

