/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId {
  public static final String SERIALIZED_NAME_PRVT_ID = "PrvtId";
  @JsonProperty(SERIALIZED_NAME_PRVT_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrIdPrvtId prvtId;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrId prvtId(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
    return this;
  }

  /**
   * Get prvtId
   * 
   * @return prvtId
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrIdPrvtId getPrvtId() {
    return prvtId;
  }

  public void setPrvtId(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfCdtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
  }

}
