/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponse
 */

public class CreditoResponse {
  public static final String SERIALIZED_NAME_DOCUMENT = "Document";
  @JsonProperty(SERIALIZED_NAME_DOCUMENT)
  @Nonnull
  private CreditoResponseDocument document;

  public CreditoResponse() {
  }

  public CreditoResponse document(@Nonnull CreditoResponseDocument document) {
    this.document = document;
    return this;
  }

  /**
   * Get document
   * 
   * @return document
   */
  @Nonnull
  public CreditoResponseDocument getDocument() {
    return document;
  }

  public void setDocument(@Nonnull CreditoResponseDocument document) {
    this.document = document;
  }
}
