/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * CreditoRequestDocumentHeaderMge
 */

public class CreditoRequestDocumentHeaderMge {
  public static final String SERIALIZED_NAME_TYPE = "Type";
  @JsonProperty(SERIALIZED_NAME_TYPE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String type;

  public static final String SERIALIZED_NAME_RO_R = "RoR";
  @JsonProperty(SERIALIZED_NAME_RO_R)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String roR;

  public static final String SERIALIZED_NAME_ID_MGE = "IdMge";
  @JsonProperty(SERIALIZED_NAME_ID_MGE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String idMge;

  public static final String SERIALIZED_NAME_OPE_DATE = "OpeDate";
  @JsonProperty(SERIALIZED_NAME_OPE_DATE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String opeDate;

  public CreditoRequestDocumentHeaderMge() {
  }

  public CreditoRequestDocumentHeaderMge type(@Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * 
   * @return type
   */
  @Nonnull
  public String getType() {
    return type;
  }

  public void setType(@Nonnull String type) {
    this.type = type;
  }

  public CreditoRequestDocumentHeaderMge roR(@Nonnull String roR) {
    this.roR = roR;
    return this;
  }

  /**
   * Get roR
   * 
   * @return roR
   */
  @Nonnull
  public String getRoR() {
    return roR;
  }

  public void setRoR(@Nonnull String roR) {
    this.roR = roR;
  }

  public CreditoRequestDocumentHeaderMge idMge(@Nonnull String idMge) {
    this.idMge = idMge;
    return this;
  }

  /**
   * Get idMge
   * 
   * @return idMge
   */
  @Nonnull
  public String getIdMge() {
    return idMge;
  }

  public void setIdMge(@Nonnull String idMge) {
    this.idMge = idMge;
  }

  public CreditoRequestDocumentHeaderMge opeDate(@Nonnull String opeDate) {
    this.opeDate = opeDate;
    return this;
  }

  /**
   * Get opeDate
   * 
   * @return opeDate
   */
  @Nonnull
  public String getOpeDate() {
    return opeDate;
  }

  public void setOpeDate(@Nonnull String opeDate) {
    this.opeDate = opeDate;
  }
}
