/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;






/**
 * CreditoRequestDocumentFIToFICstmrCdtTrf
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrf {
  public static final String SERIALIZED_NAME_GRP_HDR = "GrpHdr";
  @JsonProperty(SERIALIZED_NAME_GRP_HDR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdr grpHdr;

  public static final String SERIALIZED_NAME_CDT_TRF_TX_INF = "CdtTrfTxInf";
  @JsonProperty(SERIALIZED_NAME_CDT_TRF_TX_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtTrfTxInf;

  public CreditoRequestDocumentFIToFICstmrCdtTrf() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrf grpHdr(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
    return this;
  }

  /**
   * Get grpHdr
   * @return grpHdr
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdr getGrpHdr() {
    return grpHdr;
  }

  public void setGrpHdr(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
  }


  public CreditoRequestDocumentFIToFICstmrCdtTrf cdtTrfTxInf(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtTrfTxInf) {
    this.cdtTrfTxInf = cdtTrfTxInf;
    return this;
  }

  /**
   * Get cdtTrfTxInf
   * @return cdtTrfTxInf
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf getCdtTrfTxInf() {
    return cdtTrfTxInf;
  }

  public void setCdtTrfTxInf(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInf cdtTrfTxInf) {
    this.cdtTrfTxInf = cdtTrfTxInf;
  }
}

