/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;





/**
 * CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts
 */

public class CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts {
  public static final String SERIALIZED_NAME_ORGNL_GRP_INF = "OrgnlGrpInf";
  @JsonProperty(SERIALIZED_NAME_ORGNL_GRP_INF)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf;

  public static final String SERIALIZED_NAME_ORGNL_END_TO_END_ID = "OrgnlEndToEndId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_END_TO_END_ID)
  @Nonnull
  private String orgnlEndToEndId;

  public static final String SERIALIZED_NAME_ORGNL_TX_ID = "OrgnlTxId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_TX_ID)
  @Nonnull
  private String orgnlTxId;

  public static final String SERIALIZED_NAME_TX_STS = "TxSts";
  @JsonProperty(SERIALIZED_NAME_TX_STS)
  @Nonnull
  private String txSts;

  public static final String SERIALIZED_NAME_STS_RSN_INF = "StsRsnInf";
  @JsonProperty(SERIALIZED_NAME_STS_RSN_INF)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInf stsRsnInf;

  public static final String SERIALIZED_NAME_ACCPTNC_DT_TM = "AccptncDtTm";
  @JsonProperty(SERIALIZED_NAME_ACCPTNC_DT_TM)
  @Nonnull
  private String accptncDtTm;

  public static final String SERIALIZED_NAME_ACCT_SVCR_REF = "AcctSvcrRef";
  @JsonProperty(SERIALIZED_NAME_ACCT_SVCR_REF)
  @Nonnull
  private String acctSvcrRef;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData splmtryData;

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts orgnlGrpInf(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
    return this;
  }

  /**
   * Get orgnlGrpInf
   * @return orgnlGrpInf
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf getOrgnlGrpInf() {
    return orgnlGrpInf;
  }

  public void setOrgnlGrpInf(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts orgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
    return this;
  }

  /**
   * Get orgnlEndToEndId
   * @return orgnlEndToEndId
   */
  @Nonnull
  public String getOrgnlEndToEndId() {
    return orgnlEndToEndId;
  }

  public void setOrgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts orgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
    return this;
  }

  /**
   * Get orgnlTxId
   * @return orgnlTxId
   */
  @Nonnull
  public String getOrgnlTxId() {
    return orgnlTxId;
  }

  public void setOrgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts txSts(@Nonnull String txSts) {
    this.txSts = txSts;
    return this;
  }

  /**
   * Get txSts
   * @return txSts
   */
  @Nonnull
  public String getTxSts() {
    return txSts;
  }

  public void setTxSts(@Nonnull String txSts) {
    this.txSts = txSts;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts stsRsnInf(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
    return this;
  }

  /**
   * Get stsRsnInf
   * @return stsRsnInf
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInf getStsRsnInf() {
    return stsRsnInf;
  }

  public void setStsRsnInf(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts accptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
    return this;
  }

  /**
   * Get accptncDtTm
   * @return accptncDtTm
   */
  @Nonnull
  public String getAccptncDtTm() {
    return accptncDtTm;
  }

  public void setAccptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts acctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
    return this;
  }

  /**
   * Get acctSvcrRef
   * @return acctSvcrRef
   */
  @Nonnull
  public String getAcctSvcrRef() {
    return acctSvcrRef;
  }

  public void setAcctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
  }


  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndSts splmtryData(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * @return splmtryData
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }
}

