/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf {
  public static final String SERIALIZED_NAME_CTGY_PURP = "CtgyPurp";
  @JsonProperty(SERIALIZED_NAME_CTGY_PURP)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInf ctgyPurp(
      @Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp) {
    this.ctgyPurp = ctgyPurp;
    return this;
  }

  /**
   * Get ctgyPurp
   * 
   * @return ctgyPurp
   */
  @Nonnull
  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp getCtgyPurp() {
    return ctgyPurp;
  }

  public void setCtgyPurp(@Nonnull CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp) {
    this.ctgyPurp = ctgyPurp;
  }
}
