/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp
 */

public class CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp {
  public static final String SERIALIZED_NAME_PRTRY = "Prtry";
  @JsonProperty(SERIALIZED_NAME_PRTRY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String prtry;

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp() {
  }

  public CreditoRequestDocumentFIToFICstmrCdtTrfCdtTrfTxInfPmtTpInfCtgyPurp prtry(@Nonnull String prtry) {
    this.prtry = prtry;
    return this;
  }

  /**
   * Get prtry
   * 
   * @return prtry
   */
  @Nonnull
  public String getPrtry() {
    return prtry;
  }

  public void setPrtry(@Nonnull String prtry) {
    this.prtry = prtry;
  }
}
