/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts
 */

public class CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts {
  public static final String SERIALIZED_NAME_CONF_CODE = "ConfCode";
  @JsonProperty(SERIALIZED_NAME_CONF_CODE)
  @Nonnull
  private String confCode;

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts confCode(@Nonnull String confCode) {
    this.confCode = confCode;
    return this;
  }

  /**
   * Get confCode
   * 
   * @return confCode
   */
  @Nonnull
  public String getConfCode() {
    return confCode;
  }

  public void setConfCode(@Nonnull String confCode) {
    this.confCode = confCode;
  }

}
