/*
 * Credito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.credito;

import jakarta.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp
 */

public class CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp {
  public static final String SERIALIZED_NAME_CNTS = "Cnts";
  @JsonProperty(SERIALIZED_NAME_CNTS)
  @Nonnull
  private CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts;

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp() {
  }

  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlp cnts(
      @Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts) {
    this.cnts = cnts;
    return this;
  }

  /**
   * Get cnts
   * 
   * @return cnts
   */
  @Nonnull
  public CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts getCnts() {
    return cnts;
  }

  public void setCnts(@Nonnull CreditoResponseDocumentFIToFIPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts) {
    this.cnts = cnts;
  }
}
