/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.notificacion;





import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;



/**
 * NotificacionRequestDocumentBkToCstmrStmtSplmtryData
 */

public class NotificacionRequestDocumentBkToCstmrStmtSplmtryData {
  public static final String SERIALIZED_NAME_ENVLP = "Envlp";
 @JsonProperty(SERIALIZED_NAME_ENVLP)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String envlp;

  public NotificacionRequestDocumentBkToCstmrStmtSplmtryData() {
  }

  public NotificacionRequestDocumentBkToCstmrStmtSplmtryData envlp(@Nonnull String envlp) {
    this.envlp = envlp;
    return this;
  }

  /**
   * Get envlp
   * @return envlp
   */
  @Nonnull
  public String getEnvlp() {
    return envlp;
  }

  public void setEnvlp(@Nonnull String envlp) {
    this.envlp = envlp;
  }

}

