/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts
 */

public class NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts {
  public static final String SERIALIZED_NAME_ORGN_TRX_STS = "OrgnTrxSts";
  @JsonProperty(SERIALIZED_NAME_ORGN_TRX_STS)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String orgnTrxSts;

  public static final String SERIALIZED_NAME_STS_RSN_INF = "StsRsnInf";
  @JsonProperty(SERIALIZED_NAME_STS_RSN_INF)
  @Nonnull
  private NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxStsStsRsnInf stsRsnInf;

  public NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts() {
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts orgnTrxSts(@Nonnull String orgnTrxSts) {
    this.orgnTrxSts = orgnTrxSts;
    return this;
  }

  /**
   * Get orgnTrxSts
   * 
   * @return orgnTrxSts
   */
  @Nonnull
  public String getOrgnTrxSts() {
    return orgnTrxSts;
  }

  public void setOrgnTrxSts(@Nonnull String orgnTrxSts) {
    this.orgnTrxSts = orgnTrxSts;
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts stsRsnInf(
      @Nonnull NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
    return this;
  }

  /**
   * Get stsRsnInf
   * 
   * @return stsRsnInf
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxStsStsRsnInf getStsRsnInf() {
    return stsRsnInf;
  }

  public void setStsRsnInf(@Nonnull NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
  }
}
