/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * NotificacionRequestDocumentBkToCstmrStmt
 */

public class NotificacionRequestDocumentBkToCstmrStmt {
  public static final String SERIALIZED_NAME_MGE = "Mge";
  @JsonProperty(SERIALIZED_NAME_MGE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private NotificacionRequestDocumentBkToCstmrStmtMge mge;

  public static final String SERIALIZED_NAME_STMT = "Stmt";
  @JsonProperty(SERIALIZED_NAME_STMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private NotificacionRequestDocumentBkToCstmrStmtStmt stmt;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private NotificacionRequestDocumentBkToCstmrStmtSplmtryData splmtryData;

  public NotificacionRequestDocumentBkToCstmrStmt() {
  }

  public NotificacionRequestDocumentBkToCstmrStmt mge(@Nonnull NotificacionRequestDocumentBkToCstmrStmtMge mge) {
    this.mge = mge;
    return this;
  }

  /**
   * Get mge
   * 
   * @return mge
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmtMge getMge() {
    return mge;
  }

  public void setMge(@Nonnull NotificacionRequestDocumentBkToCstmrStmtMge mge) {
    this.mge = mge;
  }

  public NotificacionRequestDocumentBkToCstmrStmt stmt(@Nonnull NotificacionRequestDocumentBkToCstmrStmtStmt stmt) {
    this.stmt = stmt;
    return this;
  }

  /**
   * Get stmt
   * 
   * @return stmt
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmtStmt getStmt() {
    return stmt;
  }

  public void setStmt(@Nonnull NotificacionRequestDocumentBkToCstmrStmtStmt stmt) {
    this.stmt = stmt;
  }

  public NotificacionRequestDocumentBkToCstmrStmt splmtryData(
      @Nonnull NotificacionRequestDocumentBkToCstmrStmtSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * 
   * @return splmtryData
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmtSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nonnull NotificacionRequestDocumentBkToCstmrStmtSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }
}
