/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.notificacion;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * NotificacionRespuestaBkToCstmrStmtRpt
 */

public class NotificacionRespuestaBkToCstmrStmtRpt {
  public static final String SERIALIZED_NAME_STMT_RPT = "StmtRpt";
 @JsonProperty(SERIALIZED_NAME_STMT_RPT)
  @Nonnull
  private NotificacionRespuestaBkToCstmrStmtRptStmtRpt stmtRpt;

  public NotificacionRespuestaBkToCstmrStmtRpt() {
  }

  public NotificacionRespuestaBkToCstmrStmtRpt stmtRpt(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRpt stmtRpt) {
    this.stmtRpt = stmtRpt;
    return this;
  }

  /**
   * Get stmtRpt
   * @return stmtRpt
   */
  @Nonnull
  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt getStmtRpt() {
    return stmtRpt;
  }

  public void setStmtRpt(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRpt stmtRpt) {
    this.stmtRpt = stmtRpt;
  }
}

