/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * NotificacionRequestDocumentBkToCstmrStmtStmt
 */

public class NotificacionRequestDocumentBkToCstmrStmtStmt {
  public static final String SERIALIZED_NAME_ORGNL_TRX_MSG_NM_ID = "OrgnlTrxMsgNmId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_TRX_MSG_NM_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String orgnlTrxMsgNmId;

  public static final String SERIALIZED_NAME_AMT = "Amt";
  @JsonProperty(SERIALIZED_NAME_AMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String amt;

  public static final String SERIALIZED_NAME_AMT_CCY = "AmtCcy";
  @JsonProperty(SERIALIZED_NAME_AMT_CCY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String amtCcy;

  public static final String SERIALIZED_NAME_ORGN_TRX_STS = "OrgnTrxSts";
  @JsonProperty(SERIALIZED_NAME_ORGN_TRX_STS)
  @Nonnull
  private NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts orgnTrxSts;

  public NotificacionRequestDocumentBkToCstmrStmtStmt() {
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmt orgnlTrxMsgNmId(@Nonnull String orgnlTrxMsgNmId) {
    this.orgnlTrxMsgNmId = orgnlTrxMsgNmId;
    return this;
  }

  /**
   * Get orgnlTrxMsgNmId
   * 
   * @return orgnlTrxMsgNmId
   */
  @Nonnull
  public String getOrgnlTrxMsgNmId() {
    return orgnlTrxMsgNmId;
  }

  public void setOrgnlTrxMsgNmId(@Nonnull String orgnlTrxMsgNmId) {
    this.orgnlTrxMsgNmId = orgnlTrxMsgNmId;
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmt amt(@Nonnull String amt) {
    this.amt = amt;
    return this;
  }

  /**
   * Get amt
   * 
   * @return amt
   */
  @Nonnull
  public String getAmt() {
    return amt;
  }

  public void setAmt(@Nonnull String amt) {
    this.amt = amt;
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmt amtCcy(@Nonnull String amtCcy) {
    this.amtCcy = amtCcy;
    return this;
  }

  /**
   * Get amtCcy
   * 
   * @return amtCcy
   */
  @Nonnull
  public String getAmtCcy() {
    return amtCcy;
  }

  public void setAmtCcy(@Nonnull String amtCcy) {
    this.amtCcy = amtCcy;
  }

  public NotificacionRequestDocumentBkToCstmrStmtStmt orgnTrxSts(
      @Nonnull NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts orgnTrxSts) {
    this.orgnTrxSts = orgnTrxSts;
    return this;
  }

  /**
   * Get orgnTrxSts
   * 
   * @return orgnTrxSts
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts getOrgnTrxSts() {
    return orgnTrxSts;
  }

  public void setOrgnTrxSts(@Nonnull NotificacionRequestDocumentBkToCstmrStmtStmtOrgnTrxSts orgnTrxSts) {
    this.orgnTrxSts = orgnTrxSts;
  }
}
