/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * NotificacionRequestDocument
 */

public class NotificacionRequestDocument {
  public static final String SERIALIZED_NAME_BK_TO_CSTMR_STMT = "BkToCstmrStmt";
  @JsonProperty(SERIALIZED_NAME_BK_TO_CSTMR_STMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private NotificacionRequestDocumentBkToCstmrStmt bkToCstmrStmt;

  public NotificacionRequestDocument() {
  }

  public NotificacionRequestDocument bkToCstmrStmt(@Nonnull NotificacionRequestDocumentBkToCstmrStmt bkToCstmrStmt) {
    this.bkToCstmrStmt = bkToCstmrStmt;
    return this;
  }

  /**
   * Get bkToCstmrStmt
   * 
   * @return bkToCstmrStmt
   */
  @Nonnull
  public NotificacionRequestDocumentBkToCstmrStmt getBkToCstmrStmt() {
    return bkToCstmrStmt;
  }

  public void setBkToCstmrStmt(@Nonnull NotificacionRequestDocumentBkToCstmrStmt bkToCstmrStmt) {
    this.bkToCstmrStmt = bkToCstmrStmt;
  }
}
