/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.notificacion;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;

import jakarta.annotation.Nullable;

/**
 * NotificacionRespuestaBkToCstmrStmtRptStmtRptStsRsnInf
 */

public class NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInf {
  public static final String SERIALIZED_NAME_RSN = "Rsn";
 @JsonProperty(SERIALIZED_NAME_RSN)
  @Nonnull
  private NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInfRsn rsn;

  public static final String SERIALIZED_NAME_ADDTL_INF = "AddtlInf";
 @JsonProperty(SERIALIZED_NAME_ADDTL_INF)
 @Nullable
  private String addtlInf;

  public NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInf() {
  }

  public NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInf rsn(@Nonnull NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInfRsn rsn) {
    this.rsn = rsn;
    return this;
  }

  /**
   * Get rsn
   * @return rsn
   */
  @Nonnull
  public NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInfRsn getRsn() {
    return rsn;
  }

  public void setRsn(@Nonnull NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInfRsn rsn) {
    this.rsn = rsn;
  }


  public NotificacionRespuestaDocumentBkToCstmrStmtRptStmtRptStsRsnInf addtlInf(@Nullable String addtlInf) {
    this.addtlInf = addtlInf;
    return this;
  }

  /**
   * Get addtlInf
   * @return addtlInf
   */
 @Nullable
  public String getAddtlInf() {
    return addtlInf;
  }

  public void setAddtlInf(@Nullable String addtlInf) {
    this.addtlInf = addtlInf;
  }

}

