/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;





import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * NotificacionRespuestaBkToCstmrStmtRptStmtRptMge
 */

public class NotificacionRespuestaBkToCstmrStmtRptStmtRptMge {
  public static final String SERIALIZED_NAME_TYPE = "Type";
 @JsonProperty(SERIALIZED_NAME_TYPE)
  @Nonnull
  private String type;

  public static final String SERIALIZED_NAME_RO_R = "RoR";
 @JsonProperty(SERIALIZED_NAME_RO_R)
  @Nonnull
  private String roR;

  public static final String SERIALIZED_NAME_ORGNL_END_TO_END_ID = "OrgnlEndToEndId";
 @JsonProperty(SERIALIZED_NAME_ORGNL_END_TO_END_ID)
  @Nonnull
  private String orgnlEndToEndId;

  public static final String SERIALIZED_NAME_CRE_DT_TM = "CreDtTm";
 @JsonProperty(SERIALIZED_NAME_CRE_DT_TM)
  @Nonnull
  private String creDtTm;

  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge() {
  }

  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge type(@Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @Nonnull
  public String getType() {
    return type;
  }

  public void setType(@Nonnull String type) {
    this.type = type;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge roR(@Nonnull String roR) {
    this.roR = roR;
    return this;
  }

  /**
   * Get roR
   * @return roR
   */
  @Nonnull
  public String getRoR() {
    return roR;
  }

  public void setRoR(@Nonnull String roR) {
    this.roR = roR;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge orgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
    return this;
  }

  /**
   * Get orgnlEndToEndId
   * @return orgnlEndToEndId
   */
  @Nonnull
  public String getOrgnlEndToEndId() {
    return orgnlEndToEndId;
  }

  public void setOrgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge creDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
    return this;
  }

  /**
   * Get creDtTm
   * @return creDtTm
   */
  @Nonnull
  public String getCreDtTm() {
    return creDtTm;
  }

  public void setCreDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
  }

}

