/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.notificacion;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * NotificacionRequestDocumentBkToCstmrStmtMge
 */

public class NotificacionRequestDocumentBkToCstmrStmtMge {
  public static final String SERIALIZED_NAME_TYPE = "Type";
  @JsonProperty(SERIALIZED_NAME_TYPE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String type;

  public static final String SERIALIZED_NAME_RO_R = "RoR";
  @JsonProperty(SERIALIZED_NAME_RO_R)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String roR;

  public static final String SERIALIZED_NAME_END_TO_END_ID = "EndToEndId";
  @JsonProperty(SERIALIZED_NAME_END_TO_END_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String endToEndId;

  public static final String SERIALIZED_NAME_CRE_DT_TM = "CreDtTm";
  @JsonProperty(SERIALIZED_NAME_CRE_DT_TM)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String creDtTm;

  public NotificacionRequestDocumentBkToCstmrStmtMge() {
  }

  public NotificacionRequestDocumentBkToCstmrStmtMge type(@Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * 
   * @return type
   */
  @Nonnull
  public String getType() {
    return type;
  }

  public void setType(@Nonnull String type) {
    this.type = type;
  }

  public NotificacionRequestDocumentBkToCstmrStmtMge roR(@Nonnull String roR) {
    this.roR = roR;
    return this;
  }

  /**
   * Get roR
   * 
   * @return roR
   */
  @Nonnull
  public String getRoR() {
    return roR;
  }

  public void setRoR(@Nonnull String roR) {
    this.roR = roR;
  }

  public NotificacionRequestDocumentBkToCstmrStmtMge endToEndId(@Nonnull String endToEndId) {
    this.endToEndId = endToEndId;
    return this;
  }

  /**
   * Get endToEndId
   * 
   * @return endToEndId
   */
  @Nonnull
  public String getEndToEndId() {
    return endToEndId;
  }

  public void setEndToEndId(@Nonnull String endToEndId) {
    this.endToEndId = endToEndId;
  }

  public NotificacionRequestDocumentBkToCstmrStmtMge creDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
    return this;
  }

  /**
   * Get creDtTm
   * 
   * @return creDtTm
   */
  @Nonnull
  public String getCreDtTm() {
    return creDtTm;
  }

  public void setCreDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
  }
}
