/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.notificacion;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * NotificacionRespuestaBkToCstmrStmtRptStmtRpt
 */

public class NotificacionRespuestaBkToCstmrStmtRptStmtRpt {
  public static final String SERIALIZED_NAME_MGE = "Mge";
 @JsonProperty(SERIALIZED_NAME_MGE)
  @Nonnull
  private NotificacionRespuestaBkToCstmrStmtRptStmtRptMge mge;

  public static final String SERIALIZED_NAME_ORGNL_TX_ID = "OrgnlTxId";
 @JsonProperty(SERIALIZED_NAME_ORGNL_TX_ID)
  @Nonnull
  private String orgnlTxId;

  public static final String SERIALIZED_NAME_TX_STS = "TxSts";
 @JsonProperty(SERIALIZED_NAME_TX_STS)
  @Nonnull
  private String txSts;

  public static final String SERIALIZED_NAME_STS_RSN_INF = "StsRsnInf";
 @JsonProperty(SERIALIZED_NAME_STS_RSN_INF)
  @Nonnull
  private NotificacionRespuestaBkToCstmrStmtRptStmtRptStsRsnInf stsRsnInf;

  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt() {
  }

  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt mge(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRptMge mge) {
    this.mge = mge;
    return this;
  }

  /**
   * Get mge
   * @return mge
   */
  @Nonnull
  public NotificacionRespuestaBkToCstmrStmtRptStmtRptMge getMge() {
    return mge;
  }

  public void setMge(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRptMge mge) {
    this.mge = mge;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt orgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
    return this;
  }

  /**
   * Get orgnlTxId
   * @return orgnlTxId
   */
  @Nonnull
  public String getOrgnlTxId() {
    return orgnlTxId;
  }

  public void setOrgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt txSts(@Nonnull String txSts) {
    this.txSts = txSts;
    return this;
  }

  /**
   * Get txSts
   * @return txSts
   */
  @Nonnull
  public String getTxSts() {
    return txSts;
  }

  public void setTxSts(@Nonnull String txSts) {
    this.txSts = txSts;
  }


  public NotificacionRespuestaBkToCstmrStmtRptStmtRpt stsRsnInf(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRptStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
    return this;
  }

  /**
   * Get stsRsnInf
   * @return stsRsnInf
   */
  @Nonnull
  public NotificacionRespuestaBkToCstmrStmtRptStmtRptStsRsnInf getStsRsnInf() {
    return stsRsnInf;
  }

  public void setStsRsnInf(@Nonnull NotificacionRespuestaBkToCstmrStmtRptStmtRptStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
  }

}

