/*
 * Notificacion Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.notificacion;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * NotificacionRespuesta
 */

public class NotificacionRespuesta {
  public static final String SERIALIZED_NAME_BK_TO_CSTMR_STMT_RPT = "BkToCstmrStmtRpt";
 @JsonProperty(SERIALIZED_NAME_BK_TO_CSTMR_STMT_RPT)
  @Nonnull
  private NotificacionRespuestaBkToCstmrStmtRpt bkToCstmrStmtRpt;

  public NotificacionRespuesta() {
  }

  public NotificacionRespuesta bkToCstmrStmtRpt(@Nonnull NotificacionRespuestaBkToCstmrStmtRpt bkToCstmrStmtRpt) {
    this.bkToCstmrStmtRpt = bkToCstmrStmtRpt;
    return this;
  }

  /**
   * Get bkToCstmrStmtRpt
   * @return bkToCstmrStmtRpt
   */
  @Nonnull
  public NotificacionRespuestaBkToCstmrStmtRpt getBkToCstmrStmtRpt() {
    return bkToCstmrStmtRpt;
  }

  public void setBkToCstmrStmtRpt(@Nonnull NotificacionRespuestaBkToCstmrStmtRpt bkToCstmrStmtRpt) {
    this.bkToCstmrStmtRpt = bkToCstmrStmtRpt;
  }
}

