/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;

/**
 * ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf
 */

public class ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf {
  public static final String SERIALIZED_NAME_RSN = "Rsn";
  @JsonProperty(SERIALIZED_NAME_RSN)
  @Nonnull
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn;

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf() {
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf rsn(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn) {
    this.rsn = rsn;
    return this;
  }

  /**
   * Get rsn
   * @return rsn
   */
  @Nonnull
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn getRsn() {
    return rsn;
  }

  public void setRsn(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn) {
    this.rsn = rsn;
  }
}

