/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts
 */

public class ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts {
  public static final String SERIALIZED_NAME_CDTR_ACCT = "CdtrAcct";
  @JsonProperty(SERIALIZED_NAME_CDTR_ACCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String cdtrAcct;

  public static final String SERIALIZED_NAME_PRTRY = "Prtry";
  @JsonProperty(SERIALIZED_NAME_PRTRY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String prtry;

  public static final String SERIALIZED_NAME_ALIAS = "Alias";
  @JsonProperty(SERIALIZED_NAME_ALIAS)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String alias;

  public static final String SERIALIZED_NAME_VALUE = "Value";
  @JsonProperty(SERIALIZED_NAME_VALUE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String value;

  public static final String SERIALIZED_NAME_TRACK2 = "Track2";
  @JsonProperty(SERIALIZED_NAME_TRACK2)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String track2;

  public static final String SERIALIZED_NAME_REVERSAL_RSN = "ReversalRsn";
  @JsonProperty(SERIALIZED_NAME_REVERSAL_RSN)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String reversalRsn;

  public static final String SERIALIZED_NAME_ORGN_SETLMT_DT = "OrgnSetlmtDt";
  @JsonProperty(SERIALIZED_NAME_ORGN_SETLMT_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String orgnSetlmtDt;

  public static final String SERIALIZED_NAME_STTLM_DT = "SttlmDt";
  @JsonProperty(SERIALIZED_NAME_STTLM_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String sttlmDt;

  public static final String SERIALIZED_NAME_ADITIONAL_DATA = "AditionalData";
  @JsonProperty(SERIALIZED_NAME_ADITIONAL_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String aditionalData;

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts() {
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts cdtrAcct(@Nonnull String cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
    return this;
  }

  /**
   * Get cdtrAcct
   * @return cdtrAcct
   */
  @Nonnull
  public String getCdtrAcct() {
    return cdtrAcct;
  }

  public void setCdtrAcct(@Nonnull String cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts prtry(@Nonnull String prtry) {
    this.prtry = prtry;
    return this;
  }

  /**
   * Get prtry
   * @return prtry
   */
  @Nonnull
  public String getPrtry() {
    return prtry;
  }

  public void setPrtry(@Nonnull String prtry) {
    this.prtry = prtry;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts alias(@Nonnull String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @Nonnull
  public String getAlias() {
    return alias;
  }

  public void setAlias(@Nonnull String alias) {
    this.alias = alias;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts value(@Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @Nonnull
  public String getValue() {
    return value;
  }

  public void setValue(@Nonnull String value) {
    this.value = value;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts track2(@Nonnull String track2) {
    this.track2 = track2;
    return this;
  }

  /**
   * Get track2
   * @return track2
   */
  @Nonnull
  public String getTrack2() {
    return track2;
  }

  public void setTrack2(@Nonnull String track2) {
    this.track2 = track2;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts reversalRsn(@Nonnull String reversalRsn) {
    this.reversalRsn = reversalRsn;
    return this;
  }

  /**
   * Get reversalRsn
   * @return reversalRsn
   */
  @Nonnull
  public String getReversalRsn() {
    return reversalRsn;
  }

  public void setReversalRsn(@Nonnull String reversalRsn) {
    this.reversalRsn = reversalRsn;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts orgnSetlmtDt(@Nonnull String orgnSetlmtDt) {
    this.orgnSetlmtDt = orgnSetlmtDt;
    return this;
  }

  /**
   * Get orgnSetlmtDt
   * @return orgnSetlmtDt
   */
  @Nonnull
  public String getOrgnSetlmtDt() {
    return orgnSetlmtDt;
  }

  public void setOrgnSetlmtDt(@Nonnull String orgnSetlmtDt) {
    this.orgnSetlmtDt = orgnSetlmtDt;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts sttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
    return this;
  }

  /**
   * Get sttlmDt
   * @return sttlmDt
   */
  @Nonnull
  public String getSttlmDt() {
    return sttlmDt;
  }

  public void setSttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryDataEnvlpCnts aditionalData(@Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
    return this;
  }

  /**
   * Get aditionalData
   * @return aditionalData
   */
  @Nonnull
  public String getAditionalData() {
    return aditionalData;
  }

  public void setAditionalData(@Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
  }

}

