/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocumentFIToFIDbtPmtRvsl
 */

public class ReversoDebitoDocumentFIToFIDbtPmtRvsl {
  public static final String SERIALIZED_NAME_GRP_HDR = "GrpHdr";
  @JsonProperty(SERIALIZED_NAME_GRP_HDR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentFIToFIDbtPmtRvslGrpHdr grpHdr;

  public static final String SERIALIZED_NAME_TX_INF = "TxInf";
  @JsonProperty(SERIALIZED_NAME_TX_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf txInf;

  public ReversoDebitoDocumentFIToFIDbtPmtRvsl() {
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvsl grpHdr(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
    return this;
  }

  /**
   * Get grpHdr
   * @return grpHdr
   */
  @Nonnull
  public ReversoDebitoDocumentFIToFIDbtPmtRvslGrpHdr getGrpHdr() {
    return grpHdr;
  }

  public void setGrpHdr(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
  }


  public ReversoDebitoDocumentFIToFIDbtPmtRvsl txInf(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf txInf) {
    this.txInf = txInf;
    return this;
  }

  /**
   * Get txInf
   * @return txInf
   */
  @Nonnull
  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf getTxInf() {
    return txInf;
  }

  public void setTxInf(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf txInf) {
    this.txInf = txInf;
  }
}

