/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;

/**
 * ReversoDebitoResponse
 */

public class ReversoDebitoResponse {
  public static final String SERIALIZED_NAME_DOCUMENT = "Document";
  @JsonProperty(SERIALIZED_NAME_DOCUMENT)
  @Nonnull
  private ReversoDebitoResponseDocument document;

  public ReversoDebitoResponse() {
  }

  public ReversoDebitoResponse document(@Nonnull ReversoDebitoResponseDocument document) {
    this.document = document;
    return this;
  }

  /**
   * Get document
   * @return document
   */
  @Nonnull
  public ReversoDebitoResponseDocument getDocument() {
    return document;
  }

  public void setDocument(@Nonnull ReversoDebitoResponseDocument document) {
    this.document = document;
  }

}

