/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocumentHeaderOrigIdService
 */

public class ReversoDebitoDocumentHeaderOrigIdService {
  public static final String SERIALIZED_NAME_ID_SERV = "IdServ";
  @JsonProperty(SERIALIZED_NAME_ID_SERV)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String idServ;

  public static final String SERIALIZED_NAME_VERS_SERV = "VersServ";
  @JsonProperty(SERIALIZED_NAME_VERS_SERV)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String versServ;

  public ReversoDebitoDocumentHeaderOrigIdService() {
  }

  public ReversoDebitoDocumentHeaderOrigIdService idServ(@Nonnull String idServ) {
    this.idServ = idServ;
    return this;
  }

  /**
   * Get idServ
   * @return idServ
   */
  @Nonnull
  public String getIdServ() {
    return idServ;
  }

  public void setIdServ(@Nonnull String idServ) {
    this.idServ = idServ;
  }


  public ReversoDebitoDocumentHeaderOrigIdService versServ(@Nonnull String versServ) {
    this.versServ = versServ;
    return this;
  }

  /**
   * Get versServ
   * @return versServ
   */
  @Nonnull
  public String getVersServ() {
    return versServ;
  }

  public void setVersServ(@Nonnull String versServ) {
    this.versServ = versServ;
  }
}

