/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.reversoDebito;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocumentHeaderOrigId
 */

public class ReversoDebitoDocumentHeaderOrigId {
  public static final String SERIALIZED_NAME_CHANNEL = "Channel";
  @JsonProperty(SERIALIZED_NAME_CHANNEL)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String channel;

  public static final String SERIALIZED_NAME_APP = "App";
  @JsonProperty(SERIALIZED_NAME_APP)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String app;

  public static final String SERIALIZED_NAME_SERVICE = "Service";
  @JsonProperty(SERIALIZED_NAME_SERVICE)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentHeaderOrigIdService service;

  public static final String SERIALIZED_NAME_OTHER_ID = "OtherId";
  @JsonProperty(SERIALIZED_NAME_OTHER_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String otherId;

  public ReversoDebitoDocumentHeaderOrigId() {
  }

  public ReversoDebitoDocumentHeaderOrigId channel(@Nonnull String channel) {
    this.channel = channel;
    return this;
  }

  /**
   * Get channel
   * 
   * @return channel
   */
  @Nonnull
  public String getChannel() {
    return channel;
  }

  public void setChannel(@Nonnull String channel) {
    this.channel = channel;
  }

  public ReversoDebitoDocumentHeaderOrigId app(@Nonnull String app) {
    this.app = app;
    return this;
  }

  /**
   * Get app
   * 
   * @return app
   */
  @Nonnull
  public String getApp() {
    return app;
  }

  public void setApp(@Nonnull String app) {
    this.app = app;
  }

  public ReversoDebitoDocumentHeaderOrigId service(@Nonnull ReversoDebitoDocumentHeaderOrigIdService service) {
    this.service = service;
    return this;
  }

  /**
   * Get service
   * 
   * @return service
   */
  @Nonnull
  public ReversoDebitoDocumentHeaderOrigIdService getService() {
    return service;
  }

  public void setService(@Nonnull ReversoDebitoDocumentHeaderOrigIdService service) {
    this.service = service;
  }

  public ReversoDebitoDocumentHeaderOrigId otherId(@Nonnull String otherId) {
    this.otherId = otherId;
    return this;
  }

  /**
   * Get otherId
   * 
   * @return otherId
   */
  @Nonnull
  public String getOtherId() {
    return otherId;
  }

  public void setOtherId(@Nonnull String otherId) {
    this.otherId = otherId;
  }

}
