/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.reversoDebito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf
 */

public class ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf {
  public static final String SERIALIZED_NAME_ORGNL_GRP_INF = "OrgnlGrpInf";
  @JsonProperty(SERIALIZED_NAME_ORGNL_GRP_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfOrgnlGrpInf orgnlGrpInf;

  public static final String SERIALIZED_NAME_ORGNL_END_TO_END_ID = "OrgnlEndToEndId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_END_TO_END_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String orgnlEndToEndId;

  public static final String SERIALIZED_NAME_ORGNL_TX_ID = "OrgnlTxId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_TX_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String orgnlTxId;

  public static final String SERIALIZED_NAME_RVSD_INTR_BK_STTLM_AMT = "RvsdIntrBkSttlmAmt";
  @JsonProperty(SERIALIZED_NAME_RVSD_INTR_BK_STTLM_AMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String rvsdIntrBkSttlmAmt;

  public static final String SERIALIZED_NAME_RVSD_INTR_BK_STTLM_AMT_CCY = "RvsdIntrBkSttlmAmtCcy";
  @JsonProperty(SERIALIZED_NAME_RVSD_INTR_BK_STTLM_AMT_CCY)
  @Nonnull
  private String rvsdIntrBkSttlmAmtCcy;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryData splmtryData;

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf() {
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf orgnlGrpInf(
      @Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
    return this;
  }

  /**
   * Get orgnlGrpInf
   * 
   * @return orgnlGrpInf
   */
  @Nonnull
  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfOrgnlGrpInf getOrgnlGrpInf() {
    return orgnlGrpInf;
  }

  public void setOrgnlGrpInf(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf orgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
    return this;
  }

  /**
   * Get orgnlEndToEndId
   * 
   * @return orgnlEndToEndId
   */
  @Nonnull
  public String getOrgnlEndToEndId() {
    return orgnlEndToEndId;
  }

  public void setOrgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf orgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
    return this;
  }

  /**
   * Get orgnlTxId
   * 
   * @return orgnlTxId
   */
  @Nonnull
  public String getOrgnlTxId() {
    return orgnlTxId;
  }

  public void setOrgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf rvsdIntrBkSttlmAmt(@Nonnull String rvsdIntrBkSttlmAmt) {
    this.rvsdIntrBkSttlmAmt = rvsdIntrBkSttlmAmt;
    return this;
  }

  /**
   * Get rvsdIntrBkSttlmAmt
   * 
   * @return rvsdIntrBkSttlmAmt
   */
  @Nonnull
  public String getRvsdIntrBkSttlmAmt() {
    return rvsdIntrBkSttlmAmt;
  }

  public void setRvsdIntrBkSttlmAmt(@Nonnull String rvsdIntrBkSttlmAmt) {
    this.rvsdIntrBkSttlmAmt = rvsdIntrBkSttlmAmt;
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf rvsdIntrBkSttlmAmtCcy(@Nonnull String rvsdIntrBkSttlmAmtCcy) {
    this.rvsdIntrBkSttlmAmtCcy = rvsdIntrBkSttlmAmtCcy;
    return this;
  }

  /**
   * Get rvsdIntrBkSttlmAmtCcy
   * 
   * @return rvsdIntrBkSttlmAmtCcy
   */
  @Nonnull
  public String getRvsdIntrBkSttlmAmtCcy() {
    return rvsdIntrBkSttlmAmtCcy;
  }

  public void setRvsdIntrBkSttlmAmtCcy(@Nonnull String rvsdIntrBkSttlmAmtCcy) {
    this.rvsdIntrBkSttlmAmtCcy = rvsdIntrBkSttlmAmtCcy;
  }

  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInf splmtryData(
      @Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * 
   * @return splmtryData
   */
  @Nonnull
  public ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvslTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }
}
