/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;


/**
 * ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt
 */

public class ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt {
  public static final String SERIALIZED_NAME_GRP_HDR = "GrpHdr";
  @JsonProperty(SERIALIZED_NAME_GRP_HDR)
  @Nonnull
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr;

  public static final String SERIALIZED_NAME_TX_INF_AND_STS = "TxInfAndSts";
  @JsonProperty(SERIALIZED_NAME_TX_INF_AND_STS)
  @Nullable
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts;

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt() {
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt grpHdr(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
    return this;
  }

  /**
   * Get grpHdr
   * @return grpHdr
   */
  @Nonnull
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr getGrpHdr() {
    return grpHdr;
  }

  public void setGrpHdr(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
  }


  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt txInfAndSts(@Nullable ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
    return this;
  }

  /**
   * Get txInfAndSts
   * @return txInfAndSts
   */
  @Nullable
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts getTxInfAndSts() {
    return txInfAndSts;
  }

  public void setTxInfAndSts(@Nullable ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
  }
}

