/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.reversoDebito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;

/**
 * ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts
 */

public class ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts {
  public static final String SERIALIZED_NAME_ORGNL_GRP_INF = "OrgnlGrpInf";
  @JsonProperty(SERIALIZED_NAME_ORGNL_GRP_INF)
  @Nonnull
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf;

  public static final String SERIALIZED_NAME_ORGNL_END_TO_END_ID = "OrgnlEndToEndId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_END_TO_END_ID)
  @Nonnull
  private String orgnlEndToEndId;

  public static final String SERIALIZED_NAME_ORGNL_TX_ID = "OrgnlTxId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_TX_ID)
  @Nonnull
  private String orgnlTxId;

  public static final String SERIALIZED_NAME_TX_STS = "TxSts";
  @JsonProperty(SERIALIZED_NAME_TX_STS)
  @Nonnull
  private String txSts;

  public static final String SERIALIZED_NAME_ACCPTNC_DT_TM = "AccptncDtTm";
  @JsonProperty(SERIALIZED_NAME_ACCPTNC_DT_TM)
  @Nonnull
  private String accptncDtTm;

  public static final String SERIALIZED_NAME_ACCT_SVCR_REF = "AcctSvcrRef";
  @JsonProperty(SERIALIZED_NAME_ACCT_SVCR_REF)
  @Nonnull
  private String acctSvcrRef;

  public static final String SERIALIZED_NAME_STS_RSN_INF = "StsRsnInf";
  @JsonProperty(SERIALIZED_NAME_STS_RSN_INF)
  @Nonnull
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf;

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts() {
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlGrpInf(
      @Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
    return this;
  }

  /**
   * Get orgnlGrpInf
   * 
   * @return orgnlGrpInf
   */
  @Nonnull
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf getOrgnlGrpInf() {
    return orgnlGrpInf;
  }

  public void setOrgnlGrpInf(
      @Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
    return this;
  }

  /**
   * Get orgnlEndToEndId
   * 
   * @return orgnlEndToEndId
   */
  @Nonnull
  public String getOrgnlEndToEndId() {
    return orgnlEndToEndId;
  }

  public void setOrgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
    return this;
  }

  /**
   * Get orgnlTxId
   * 
   * @return orgnlTxId
   */
  @Nonnull
  public String getOrgnlTxId() {
    return orgnlTxId;
  }

  public void setOrgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txSts(@Nonnull String txSts) {
    this.txSts = txSts;
    return this;
  }

  /**
   * Get txSts
   * 
   * @return txSts
   */
  @Nonnull
  public String getTxSts() {
    return txSts;
  }

  public void setTxSts(@Nonnull String txSts) {
    this.txSts = txSts;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts accptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
    return this;
  }

  /**
   * Get accptncDtTm
   * 
   * @return accptncDtTm
   */
  @Nonnull
  public String getAccptncDtTm() {
    return accptncDtTm;
  }

  public void setAccptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts acctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
    return this;
  }

  /**
   * Get acctSvcrRef
   * 
   * @return acctSvcrRef
   */
  @Nonnull
  public String getAcctSvcrRef() {
    return acctSvcrRef;
  }

  public void setAcctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
  }

  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts stsRsnInf(
      @Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
    return this;
  }

  /**
   * Get stsRsnInf
   * 
   * @return stsRsnInf
   */
  @Nonnull
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf getStsRsnInf() {
    return stsRsnInf;
  }

  public void setStsRsnInf(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
  }
}
