/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * ReversoDebitoDocument
 */

public class ReversoDebitoDocument {
  public static final String SERIALIZED_NAME_HEADER = "Header";
  @JsonProperty(SERIALIZED_NAME_HEADER)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentHeader header;

  public static final String SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_RVSL = "FIToFIDbtPmtRvsl";
  @JsonProperty(SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_RVSL)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private ReversoDebitoDocumentFIToFIDbtPmtRvsl fiToFIDbtPmtRvsl;

  public ReversoDebitoDocument() {
  }

  public ReversoDebitoDocument header(@Nonnull ReversoDebitoDocumentHeader header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @Nonnull
  public ReversoDebitoDocumentHeader getHeader() {
    return header;
  }

  public void setHeader(@Nonnull ReversoDebitoDocumentHeader header) {
    this.header = header;
  }


  public ReversoDebitoDocument fiToFIDbtPmtRvsl(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvsl fiToFIDbtPmtRvsl) {
    this.fiToFIDbtPmtRvsl = fiToFIDbtPmtRvsl;
    return this;
  }

  /**
   * Get fiToFIDbtPmtRvsl
   * @return fiToFIDbtPmtRvsl
   */
  @Nonnull
  public ReversoDebitoDocumentFIToFIDbtPmtRvsl getFiToFIDbtPmtRvsl() {
    return fiToFIDbtPmtRvsl;
  }

  public void setFiToFIDbtPmtRvsl(@Nonnull ReversoDebitoDocumentFIToFIDbtPmtRvsl fiToFIDbtPmtRvsl) {
    this.fiToFIDbtPmtRvsl = fiToFIDbtPmtRvsl;
  }

}

