/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

/**
 * ReversoDebitoResponseDocumentHeader
 */

public class ReversoDebitoResponseDocumentHeader {
  public static final String SERIALIZED_NAME_ORIG_ID = "OrigId";
  @JsonProperty(SERIALIZED_NAME_ORIG_ID)
  @Nonnull
  private ReversoDebitoResponseDocumentHeaderOrigId origId;

  public static final String SERIALIZED_NAME_SENDER = "Sender";
  @JsonProperty(SERIALIZED_NAME_SENDER)
  @Nonnull
  private String sender;

  public static final String SERIALIZED_NAME_RECEIVER = "Receiver";
  @JsonProperty(SERIALIZED_NAME_RECEIVER)
  @Nonnull
  private String receiver;

  public static final String SERIALIZED_NAME_MGE = "Mge";
  @JsonProperty(SERIALIZED_NAME_MGE)
  @Nonnull
  private ReversoDebitoResponseDocumentHeaderMge mge;

  public static final String SERIALIZED_NAME_PSSBL_DPLCT = "PssblDplct";
  @JsonProperty(SERIALIZED_NAME_PSSBL_DPLCT)
  @Nonnull
  private String pssblDplct;

  public static final String SERIALIZED_NAME_PRTY = "Prty";
  @JsonProperty(SERIALIZED_NAME_PRTY)
  @Nullable
  private String prty;

  public ReversoDebitoResponseDocumentHeader() {
  }

  public ReversoDebitoResponseDocumentHeader origId(@Nonnull ReversoDebitoResponseDocumentHeaderOrigId origId) {
    this.origId = origId;
    return this;
  }

  /**
   * Get origId
   * @return origId
   */
  @Nonnull
  public ReversoDebitoResponseDocumentHeaderOrigId getOrigId() {
    return origId;
  }

  public void setOrigId(@Nonnull ReversoDebitoResponseDocumentHeaderOrigId origId) {
    this.origId = origId;
  }


  public ReversoDebitoResponseDocumentHeader sender(@Nonnull String sender) {
    this.sender = sender;
    return this;
  }

  /**
   * Get sender
   * @return sender
   */
  @Nonnull
  public String getSender() {
    return sender;
  }

  public void setSender(@Nonnull String sender) {
    this.sender = sender;
  }


  public ReversoDebitoResponseDocumentHeader receiver(@Nonnull String receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * Get receiver
   * @return receiver
   */
  @Nonnull
  public String getReceiver() {
    return receiver;
  }

  public void setReceiver(@Nonnull String receiver) {
    this.receiver = receiver;
  }


  public ReversoDebitoResponseDocumentHeader mge(@Nonnull ReversoDebitoResponseDocumentHeaderMge mge) {
    this.mge = mge;
    return this;
  }

  /**
   * Get mge
   * @return mge
   */
  @Nonnull
  public ReversoDebitoResponseDocumentHeaderMge getMge() {
    return mge;
  }

  public void setMge(@Nonnull ReversoDebitoResponseDocumentHeaderMge mge) {
    this.mge = mge;
  }


  public ReversoDebitoResponseDocumentHeader pssblDplct(@Nonnull String pssblDplct) {
    this.pssblDplct = pssblDplct;
    return this;
  }

  /**
   * Get pssblDplct
   * @return pssblDplct
   */
  @Nonnull
  public String getPssblDplct() {
    return pssblDplct;
  }

  public void setPssblDplct(@Nonnull String pssblDplct) {
    this.pssblDplct = pssblDplct;
  }


  public ReversoDebitoResponseDocumentHeader prty(@Nullable String prty) {
    this.prty = prty;
    return this;
  }

  /**
   * Get prty
   * @return prty
   */
  @Nullable
  public String getPrty() {
    return prty;
  }

  public void setPrty(@Nullable String prty) {
    this.prty = prty;
  }
}

