/*
 * Reverso Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.reversoDebito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;

/**
 * ReversoDebitoResponseDocument
 */

public class ReversoDebitoResponseDocument {
  public static final String SERIALIZED_NAME_HEADER = "Header";
  @JsonProperty(SERIALIZED_NAME_HEADER)
  @Nonnull
  private ReversoDebitoResponseDocumentHeader header;

  public static final String SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_STS_RPT = "FIToFIDbtPmtStsRpt";
  @JsonProperty(SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_STS_RPT)
  @Nonnull
  private ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt;

  public ReversoDebitoResponseDocument() {
  }

  public ReversoDebitoResponseDocument header(@Nonnull ReversoDebitoResponseDocumentHeader header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @Nonnull
  public ReversoDebitoResponseDocumentHeader getHeader() {
    return header;
  }

  public void setHeader(@Nonnull ReversoDebitoResponseDocumentHeader header) {
    this.header = header;
  }


  public ReversoDebitoResponseDocument fiToFIDbtPmtStsRpt(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt) {
    this.fiToFIDbtPmtStsRpt = fiToFIDbtPmtStsRpt;
    return this;
  }

  /**
   * Get fiToFIDbtPmtStsRpt
   * @return fiToFIDbtPmtStsRpt
   */
  @Nonnull
  public ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt getFiToFIDbtPmtStsRpt() {
    return fiToFIDbtPmtStsRpt;
  }

  public void setFiToFIDbtPmtStsRpt(@Nonnull ReversoDebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt) {
    this.fiToFIDbtPmtStsRpt = fiToFIDbtPmtStsRpt;
  }

}

