/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgt
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgt {
  public static final String SERIALIZED_NAME_FIN_INSTN_ID = "FinInstnId";
 @JsonProperty(SERIALIZED_NAME_FIN_INSTN_ID)
 @Nullable
  private DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId finInstnId;

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgt() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgt finInstnId(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId finInstnId) {
    this.finInstnId = finInstnId;
    return this;
  }

  /**
   * Get finInstnId
   * @return finInstnId
   */
 @Nullable
  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId getFinInstnId() {
    return finInstnId;
  }

  public void setFinInstnId(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId finInstnId) {
    this.finInstnId = finInstnId;
  }


}

