/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf {
  public static final String SERIALIZED_NAME_RSN = "Rsn";
 @JsonProperty(SERIALIZED_NAME_RSN)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn;

  public static final String SERIALIZED_NAME_ADDTL_INF = "AddtlInf";
 @JsonProperty(SERIALIZED_NAME_ADDTL_INF)
  @Nonnull
  private String addtlInf;

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf rsn(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn) {
    this.rsn = rsn;
    return this;
  }

  /**
   * Get rsn
   * @return rsn
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn getRsn() {
    return rsn;
  }

  public void setRsn(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInfRsn rsn) {
    this.rsn = rsn;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf addtlInf(@Nonnull String addtlInf) {
    this.addtlInf = addtlInf;
    return this;
  }

  /**
   * Get addtlInf
   * @return addtlInf
   */
  @Nonnull
  public String getAddtlInf() {
    return addtlInf;
  }

  public void setAddtlInf(@Nonnull String addtlInf) {
    this.addtlInf = addtlInf;
  }
}

