/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * DebitoResponseDocument
 */

public class DebitoResponseDocument {
  public static final String SERIALIZED_NAME_HEADER = "Header";
 @JsonProperty(SERIALIZED_NAME_HEADER)
  @Nonnull
  private DebitoResponseDocumentHeader header;

  public static final String SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_STS_RPT = "FIToFIDbtPmtStsRpt";
 @JsonProperty(SERIALIZED_NAME_FI_TO_F_I_DBT_PMT_STS_RPT)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt;

  public DebitoResponseDocument() {
  }

  public DebitoResponseDocument header(@Nonnull DebitoResponseDocumentHeader header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @Nonnull
  public DebitoResponseDocumentHeader getHeader() {
    return header;
  }

  public void setHeader(@Nonnull DebitoResponseDocumentHeader header) {
    this.header = header;
  }


  public DebitoResponseDocument fiToFIDbtPmtStsRpt(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt) {
    this.fiToFIDbtPmtStsRpt = fiToFIDbtPmtStsRpt;
    return this;
  }

  /**
   * Get fiToFIDbtPmtStsRpt
   * @return fiToFIDbtPmtStsRpt
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRpt getFiToFIDbtPmtStsRpt() {
    return fiToFIDbtPmtStsRpt;
  }

  public void setFiToFIDbtPmtStsRpt(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRpt fiToFIDbtPmtStsRpt) {
    this.fiToFIDbtPmtStsRpt = fiToFIDbtPmtStsRpt;
  }

}

