/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf {
  public static final String SERIALIZED_NAME_CTGY_PURP = "CtgyPurp";
 @JsonProperty(SERIALIZED_NAME_CTGY_PURP)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf ctgyPurp(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp) {
    this.ctgyPurp = ctgyPurp;
    return this;
  }

  /**
   * Get ctgyPurp
   * @return ctgyPurp
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInfCtgyPurp getCtgyPurp() {
    return ctgyPurp;
  }

  public void setCtgyPurp(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInfCtgyPurp ctgyPurp) {
    this.ctgyPurp = ctgyPurp;
  }

}

