/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts {
  public static final String SERIALIZED_NAME_TRACK2 = "Track2";
  @JsonProperty(SERIALIZED_NAME_TRACK2)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String track2;

  public static final String SERIALIZED_NAME_DBT_CRED = "DbtCred";
  @JsonProperty(SERIALIZED_NAME_DBT_CRED)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String dbtCred;

  public static final String SERIALIZED_NAME_STTLM_DT = "SttlmDt";
  @JsonProperty(SERIALIZED_NAME_STTLM_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String sttlmDt;

  public static final String SERIALIZED_NAME_ADITIONAL_DATA = "AditionalData";
  @JsonProperty(SERIALIZED_NAME_ADITIONAL_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String aditionalData;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts track2(@Nonnull String track2) {
    this.track2 = track2;
    return this;
  }

  /**
   * Get track2
   * 
   * @return track2
   */
  @Nonnull
  public String getTrack2() {
    return track2;
  }

  public void setTrack2(@Nonnull String track2) {
    this.track2 = track2;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts dbtCred(@Nonnull String dbtCred) {
    this.dbtCred = dbtCred;
    return this;
  }

  /**
   * Get dbtCred
   * 
   * @return dbtCred
   */
  @Nonnull
  public String getDbtCred() {
    return dbtCred;
  }

  public void setDbtCred(@Nonnull String dbtCred) {
    this.dbtCred = dbtCred;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts sttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
    return this;
  }

  /**
   * Get sttlmDt
   * 
   * @return sttlmDt
   */
  @Nonnull
  public String getSttlmDt() {
    return sttlmDt;
  }

  public void setSttlmDt(@Nonnull String sttlmDt) {
    this.sttlmDt = sttlmDt;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlpCnts aditionalData(
      @Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
    return this;
  }

  /**
   * Get aditionalData
   * 
   * @return aditionalData
   */
  @Nonnull
  public String getAditionalData() {
    return aditionalData;
  }

  public void setAditionalData(@Nonnull String aditionalData) {
    this.aditionalData = aditionalData;
  }

}
