/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocument
 */

public class DebitoRequestDocument {
  public static final String SERIALIZED_NAME_HEADER = "Header";
  @JsonProperty(SERIALIZED_NAME_HEADER)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentHeader header;

  public static final String SERIALIZED_NAME_FI_TO_F_I_CSTMR_DBT_TRF = "FIToFICstmrDbtTrf";
  @JsonProperty(SERIALIZED_NAME_FI_TO_F_I_CSTMR_DBT_TRF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrf fiToFICstmrDbtTrf;

  public DebitoRequestDocument() {
  }

  public DebitoRequestDocument header(@Nonnull DebitoRequestDocumentHeader header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * 
   * @return header
   */
  @Nonnull
  public DebitoRequestDocumentHeader getHeader() {
    return header;
  }

  public void setHeader(@Nonnull DebitoRequestDocumentHeader header) {
    this.header = header;
  }

  public DebitoRequestDocument fiToFICstmrDbtTrf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrf fiToFICstmrDbtTrf) {
    this.fiToFICstmrDbtTrf = fiToFICstmrDbtTrf;
    return this;
  }

  /**
   * Get fiToFICstmrDbtTrf
   * 
   * @return fiToFICstmrDbtTrf
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrf getFiToFICstmrDbtTrf() {
    return fiToFICstmrDbtTrf;
  }

  public void setFiToFICstmrDbtTrf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrf fiToFICstmrDbtTrf) {
    this.fiToFICstmrDbtTrf = fiToFICstmrDbtTrf;
  }

}
