/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;





import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId {
  public static final String SERIALIZED_NAME_END_TO_END_ID = "EndToEndId";
 @JsonProperty(SERIALIZED_NAME_END_TO_END_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String endToEndId;

  public static final String SERIALIZED_NAME_TX_ID = "TxId";
 @JsonProperty(SERIALIZED_NAME_TX_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String txId;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId endToEndId(@Nonnull String endToEndId) {
    this.endToEndId = endToEndId;
    return this;
  }

  /**
   * Get endToEndId
   * @return endToEndId
   */
  @Nonnull
  public String getEndToEndId() {
    return endToEndId;
  }

  public void setEndToEndId(@Nonnull String endToEndId) {
    this.endToEndId = endToEndId;
  }


  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId txId(@Nonnull String txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   */
  @Nonnull
  public String getTxId() {
    return txId;
  }

  public void setTxId(@Nonnull String txId) {
    this.txId = txId;
  }

}

