/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf {
  public static final String SERIALIZED_NAME_STTLM_MTD = "SttlmMtd";
  @JsonProperty(SERIALIZED_NAME_STTLM_MTD)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
   private String sttlmMtd;

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf sttlmMtd(@Nonnull String sttlmMtd) {
    this.sttlmMtd = sttlmMtd;
    return this;
  }

  /**
   * Get sttlmMtd
   * 
   * @return sttlmMtd
   */
  @Nonnull
  public String getSttlmMtd() {
    return sttlmMtd;
  }

  public void setSttlmMtd(@Nonnull String sttlmMtd) {
    this.sttlmMtd = sttlmMtd;
  }
}
