/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct {
  public static final String SERIALIZED_NAME_ID = "Id";
  @JsonProperty(SERIALIZED_NAME_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcctId id;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct id(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcctId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * 
   * @return id
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcctId getId() {
    return id;
  }

  public void setId(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcctId id) {
    this.id = id;
  }

}
