/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf {
  public static final String SERIALIZED_NAME_PMT_ID = "PmtId";
  @JsonProperty(SERIALIZED_NAME_PMT_ID)
  @Nonnull
  
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId pmtId;

  public static final String SERIALIZED_NAME_PMT_TP_INF = "PmtTpInf";
  @JsonProperty(SERIALIZED_NAME_PMT_TP_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf pmtTpInf;

  public static final String SERIALIZED_NAME_INTR_BK_STTLM_AMT = "IntrBkSttlmAmt";
  @JsonProperty(SERIALIZED_NAME_INTR_BK_STTLM_AMT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intrBkSttlmAmt;

  public static final String SERIALIZED_NAME_INTR_BK_STTLM_AMT_CCY = "IntrBkSttlmAmtCcy";
  @JsonProperty(SERIALIZED_NAME_INTR_BK_STTLM_AMT_CCY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intrBkSttlmAmtCcy;

  public static final String SERIALIZED_NAME_INTR_BK_STTLM_DT = "IntrBkSttlmDt";
  @JsonProperty(SERIALIZED_NAME_INTR_BK_STTLM_DT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String intrBkSttlmDt;

  public static final String SERIALIZED_NAME_CHRGS_INF = "ChrgsInf";
  @JsonProperty(SERIALIZED_NAME_CHRGS_INF)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf chrgsInf;

  public static final String SERIALIZED_NAME_DBTR = "Dbtr";
  @JsonProperty(SERIALIZED_NAME_DBTR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr dbtr;

  public static final String SERIALIZED_NAME_DBTR_ACCT = "DbtrAcct";
  @JsonProperty(SERIALIZED_NAME_DBTR_ACCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct dbtrAcct;

  public static final String SERIALIZED_NAME_DBTR_AGT = "DbtrAgt";
  @JsonProperty(SERIALIZED_NAME_DBTR_AGT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt dbtrAgt;

  public static final String SERIALIZED_NAME_CDTR_AGT = "CdtrAgt";
  @JsonProperty(SERIALIZED_NAME_CDTR_AGT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt cdtrAgt;

  public static final String SERIALIZED_NAME_CDTR = "Cdtr";
  @JsonProperty(SERIALIZED_NAME_CDTR)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtr cdtr;

  public static final String SERIALIZED_NAME_CDTR_ACCT = "CdtrAcct";
  @JsonProperty(SERIALIZED_NAME_CDTR_ACCT)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrAcct cdtrAcct;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData splmtryData;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf pmtId(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId pmtId) {
    this.pmtId = pmtId;
    return this;
  }

  /**
   * Get pmtId
   * 
   * @return pmtId
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId getPmtId() {
    return pmtId;
  }

  public void setPmtId(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtId pmtId) {
    this.pmtId = pmtId;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf pmtTpInf(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf pmtTpInf) {
    this.pmtTpInf = pmtTpInf;
    return this;
  }

  /**
   * Get pmtTpInf
   * 
   * @return pmtTpInf
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf getPmtTpInf() {
    return pmtTpInf;
  }

  public void setPmtTpInf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfPmtTpInf pmtTpInf) {
    this.pmtTpInf = pmtTpInf;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf intrBkSttlmAmt(@Nonnull String intrBkSttlmAmt) {
    this.intrBkSttlmAmt = intrBkSttlmAmt;
    return this;
  }

  /**
   * Get intrBkSttlmAmt
   * 
   * @return intrBkSttlmAmt
   */
  @Nonnull
  public String getIntrBkSttlmAmt() {
    return intrBkSttlmAmt;
  }

  public void setIntrBkSttlmAmt(@Nonnull String intrBkSttlmAmt) {
    this.intrBkSttlmAmt = intrBkSttlmAmt;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf intrBkSttlmAmtCcy(@Nonnull String intrBkSttlmAmtCcy) {
    this.intrBkSttlmAmtCcy = intrBkSttlmAmtCcy;
    return this;
  }

  /**
   * Get intrBkSttlmAmtCcy
   * 
   * @return intrBkSttlmAmtCcy
   */
  @Nonnull
  public String getIntrBkSttlmAmtCcy() {
    return intrBkSttlmAmtCcy;
  }

  public void setIntrBkSttlmAmtCcy(@Nonnull String intrBkSttlmAmtCcy) {
    this.intrBkSttlmAmtCcy = intrBkSttlmAmtCcy;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf intrBkSttlmDt(@Nonnull String intrBkSttlmDt) {
    this.intrBkSttlmDt = intrBkSttlmDt;
    return this;
  }

  /**
   * Get intrBkSttlmDt
   * 
   * @return intrBkSttlmDt
   */
  @Nonnull
  public String getIntrBkSttlmDt() {
    return intrBkSttlmDt;
  }

  public void setIntrBkSttlmDt(@Nonnull String intrBkSttlmDt) {
    this.intrBkSttlmDt = intrBkSttlmDt;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf chrgsInf(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf chrgsInf) {
    this.chrgsInf = chrgsInf;
    return this;
  }

  /**
   * Get chrgsInf
   * 
   * @return chrgsInf
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf getChrgsInf() {
    return chrgsInf;
  }

  public void setChrgsInf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf chrgsInf) {
    this.chrgsInf = chrgsInf;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf dbtr(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr dbtr) {
    this.dbtr = dbtr;
    return this;
  }

  /**
   * Get dbtr
   * 
   * @return dbtr
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr getDbtr() {
    return dbtr;
  }

  public void setDbtr(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr dbtr) {
    this.dbtr = dbtr;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf dbtrAcct(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct dbtrAcct) {
    this.dbtrAcct = dbtrAcct;
    return this;
  }

  /**
   * Get dbtrAcct
   * 
   * @return dbtrAcct
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct getDbtrAcct() {
    return dbtrAcct;
  }

  public void setDbtrAcct(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAcct dbtrAcct) {
    this.dbtrAcct = dbtrAcct;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf dbtrAgt(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt dbtrAgt) {
    this.dbtrAgt = dbtrAgt;
    return this;
  }

  /**
   * Get dbtrAgt
   * 
   * @return dbtrAgt
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt getDbtrAgt() {
    return dbtrAgt;
  }

  public void setDbtrAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt dbtrAgt) {
    this.dbtrAgt = dbtrAgt;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf cdtrAgt(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt cdtrAgt) {
    this.cdtrAgt = cdtrAgt;
    return this;
  }

  /**
   * Get cdtrAgt
   * 
   * @return cdtrAgt
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt getCdtrAgt() {
    return cdtrAgt;
  }

  public void setCdtrAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt cdtrAgt) {
    this.cdtrAgt = cdtrAgt;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf cdtr(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtr cdtr) {
    this.cdtr = cdtr;
    return this;
  }

  /**
   * Get cdtr
   * 
   * @return cdtr
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtr getCdtr() {
    return cdtr;
  }

  public void setCdtr(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtr cdtr) {
    this.cdtr = cdtr;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf cdtrAcct(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrAcct cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
    return this;
  }

  /**
   * Get cdtrAcct
   * 
   * @return cdtrAcct
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrAcct getCdtrAcct() {
    return cdtrAcct;
  }

  public void setCdtrAcct(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrAcct cdtrAcct) {
    this.cdtrAcct = cdtrAcct;
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInf splmtryData(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * 
   * @return splmtryData
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }

}
