/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId {
  public static final String SERIALIZED_NAME_PRVT_ID = "PrvtId";
 @JsonProperty(SERIALIZED_NAME_PRVT_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrIdPrvtId prvtId;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId prvtId(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
    return this;
  }

  /**
   * Get prvtId
   * @return prvtId
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrIdPrvtId getPrvtId() {
    return prvtId;
  }

  public void setPrvtId(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
  }

}

