/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;



/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData {
  public static final String SERIALIZED_NAME_ENVLP = "Envlp";
 @JsonProperty(SERIALIZED_NAME_ENVLP)
 @Nullable
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp;

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData envlp(@Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
    return this;
  }

  /**
   * Get envlp
   * @return envlp
   */
 @Nullable
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp getEnvlp() {
    return envlp;
  }

  public void setEnvlp(@Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
  }


}

