/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;





import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.constraints.NotNull;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf {
  public static final String SERIALIZED_NAME_AMT_CCY = "AmtCcy";
 @JsonProperty(SERIALIZED_NAME_AMT_CCY)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  private String amtCcy;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfChrgsInf amtCcy(@Nonnull String amtCcy) {
    this.amtCcy = amtCcy;
    return this;
  }

  /**
   * Get amtCcy
   * @return amtCcy
   */
  @Nonnull
  public String getAmtCcy() {
    return amtCcy;
  }

  public void setAmtCcy(@Nonnull String amtCcy) {
    this.amtCcy = amtCcy;
  }
}

