/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRpt
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRpt {
  public static final String SERIALIZED_NAME_GRP_HDR = "GrpHdr";
 @JsonProperty(SERIALIZED_NAME_GRP_HDR)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr;

  public static final String SERIALIZED_NAME_TX_INF_AND_STS = "TxInfAndSts";
 @JsonProperty(SERIALIZED_NAME_TX_INF_AND_STS)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts;

  public DebitoResponseDocumentFIToFIDbtPmtStsRpt() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRpt grpHdr(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
    return this;
  }

  /**
   * Get grpHdr
   * @return grpHdr
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr getGrpHdr() {
    return grpHdr;
  }

  public void setGrpHdr(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr grpHdr) {
    this.grpHdr = grpHdr;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRpt txInfAndSts(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
    return this;
  }

  /**
   * Get txInfAndSts
   * @return txInfAndSts
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts getTxInfAndSts() {
    return txInfAndSts;
  }

  public void setTxInfAndSts(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txInfAndSts) {
    this.txInfAndSts = txInfAndSts;
  }

}

