/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;








import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;



/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr {
  public static final String SERIALIZED_NAME_MSG_ID = "MsgId";
 @JsonProperty(SERIALIZED_NAME_MSG_ID)
  @Nonnull
  private String msgId;

  public static final String SERIALIZED_NAME_CRE_DT_TM = "CreDtTm";
 @JsonProperty(SERIALIZED_NAME_CRE_DT_TM)
  @Nonnull
  private String creDtTm;

  public static final String SERIALIZED_NAME_NB_OF_TXS = "NbOfTxs";
 @JsonProperty(SERIALIZED_NAME_NB_OF_TXS)
  @Nonnull
  private String nbOfTxs;

  public static final String SERIALIZED_NAME_STT_INF = "SttInf";
 @JsonProperty(SERIALIZED_NAME_STT_INF)
  @Nonnull
  private DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf sttInf;

  public static final String SERIALIZED_NAME_INSTG_AGT = "InstgAgt";
 @JsonProperty(SERIALIZED_NAME_INSTG_AGT)
  @Nonnull
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt instgAgt;

  public static final String SERIALIZED_NAME_INSTD_AGT = "InstdAgt";
 @JsonProperty(SERIALIZED_NAME_INSTD_AGT)
  @Nonnull
  private DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt instdAgt;

  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr msgId(@Nonnull String msgId) {
    this.msgId = msgId;
    return this;
  }

  /**
   * Get msgId
   * @return msgId
   */
  @Nonnull
  public String getMsgId() {
    return msgId;
  }

  public void setMsgId(@Nonnull String msgId) {
    this.msgId = msgId;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr creDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
    return this;
  }

  /**
   * Get creDtTm
   * @return creDtTm
   */
  @Nonnull
  public String getCreDtTm() {
    return creDtTm;
  }

  public void setCreDtTm(@Nonnull String creDtTm) {
    this.creDtTm = creDtTm;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr nbOfTxs(@Nonnull String nbOfTxs) {
    this.nbOfTxs = nbOfTxs;
    return this;
  }

  /**
   * Get nbOfTxs
   * @return nbOfTxs
   */
  @Nonnull
  public String getNbOfTxs() {
    return nbOfTxs;
  }

  public void setNbOfTxs(@Nonnull String nbOfTxs) {
    this.nbOfTxs = nbOfTxs;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr sttInf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf sttInf) {
    this.sttInf = sttInf;
    return this;
  }

  /**
   * Get sttInf
   * @return sttInf
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf getSttInf() {
    return sttInf;
  }

  public void setSttInf(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrSttInf sttInf) {
    this.sttInf = sttInf;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr instgAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt instgAgt) {
    this.instgAgt = instgAgt;
    return this;
  }

  /**
   * Get instgAgt
   * @return instgAgt
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt getInstgAgt() {
    return instgAgt;
  }

  public void setInstgAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrAgt instgAgt) {
    this.instgAgt = instgAgt;
  }


  public DebitoResponseDocumentFIToFIDbtPmtStsRptGrpHdr instdAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt instdAgt) {
    this.instdAgt = instdAgt;
    return this;
  }

  /**
   * Get instdAgt
   * @return instdAgt
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt getInstdAgt() {
    return instdAgt;
  }

  public void setInstdAgt(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstdAgt instdAgt) {
    this.instdAgt = instdAgt;
  }

}

