/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;





import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtIdOthr
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtIdOthr {
  public static final String SERIALIZED_NAME_ID = "Id";
 @JsonProperty(SERIALIZED_NAME_ID)
 @Nullable
  private String id;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtIdOthr() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtIdOthr id(@Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
 @Nullable
  public String getId() {
    return id;
  }

  public void setId(@Nullable String id) {
    this.id = id;
  }

}

