/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts {
  public static final String SERIALIZED_NAME_ORGNL_GRP_INF = "OrgnlGrpInf";
  @JsonProperty(SERIALIZED_NAME_ORGNL_GRP_INF)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf;

  public static final String SERIALIZED_NAME_ORGNL_END_TO_END_ID = "OrgnlEndToEndId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_END_TO_END_ID)
  @Nonnull
  private String orgnlEndToEndId;

  public static final String SERIALIZED_NAME_ORGNL_TX_ID = "OrgnlTxId";
  @JsonProperty(SERIALIZED_NAME_ORGNL_TX_ID)
  @Nonnull
  private String orgnlTxId;

  public static final String SERIALIZED_NAME_TX_STS = "TxSts";
  @JsonProperty(SERIALIZED_NAME_TX_STS)
  @Nonnull
  private String txSts;

  public static final String SERIALIZED_NAME_STS_RSN_INF = "StsRsnInf";
  @JsonProperty(SERIALIZED_NAME_STS_RSN_INF)
  @Nonnull
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf;

  public static final String SERIALIZED_NAME_ACCPTNC_DT_TM = "AccptncDtTm";
  @JsonProperty(SERIALIZED_NAME_ACCPTNC_DT_TM)
  @Nonnull
  private String accptncDtTm;

  public static final String SERIALIZED_NAME_ACCT_SVCR_REF = "AcctSvcrRef";
  @JsonProperty(SERIALIZED_NAME_ACCT_SVCR_REF)
  @Nonnull
  private String acctSvcrRef;

  public static final String SERIALIZED_NAME_SPLMTRY_DATA = "SplmtryData";
  @JsonProperty(SERIALIZED_NAME_SPLMTRY_DATA)
  @Nullable
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData splmtryData;

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlGrpInf(
      @Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
    return this;
  }

  /**
   * Get orgnlGrpInf
   * 
   * @return orgnlGrpInf
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf getOrgnlGrpInf() {
    return orgnlGrpInf;
  }

  public void setOrgnlGrpInf(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsOrgnlGrpInf orgnlGrpInf) {
    this.orgnlGrpInf = orgnlGrpInf;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
    return this;
  }

  /**
   * Get orgnlEndToEndId
   * 
   * @return orgnlEndToEndId
   */
  @Nonnull
  public String getOrgnlEndToEndId() {
    return orgnlEndToEndId;
  }

  public void setOrgnlEndToEndId(@Nonnull String orgnlEndToEndId) {
    this.orgnlEndToEndId = orgnlEndToEndId;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts orgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
    return this;
  }

  /**
   * Get orgnlTxId
   * 
   * @return orgnlTxId
   */
  @Nonnull
  public String getOrgnlTxId() {
    return orgnlTxId;
  }

  public void setOrgnlTxId(@Nonnull String orgnlTxId) {
    this.orgnlTxId = orgnlTxId;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts txSts(@Nonnull String txSts) {
    this.txSts = txSts;
    return this;
  }

  /**
   * Get txSts
   * 
   * @return txSts
   */
  @Nonnull
  public String getTxSts() {
    return txSts;
  }

  public void setTxSts(@Nonnull String txSts) {
    this.txSts = txSts;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts stsRsnInf(
      @Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
    return this;
  }

  /**
   * Get stsRsnInf
   * 
   * @return stsRsnInf
   */
  @Nonnull
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf getStsRsnInf() {
    return stsRsnInf;
  }

  public void setStsRsnInf(@Nonnull DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsStsRsnInf stsRsnInf) {
    this.stsRsnInf = stsRsnInf;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts accptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
    return this;
  }

  /**
   * Get accptncDtTm
   * 
   * @return accptncDtTm
   */
  @Nonnull
  public String getAccptncDtTm() {
    return accptncDtTm;
  }

  public void setAccptncDtTm(@Nonnull String accptncDtTm) {
    this.accptncDtTm = accptncDtTm;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts acctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
    return this;
  }

  /**
   * Get acctSvcrRef
   * 
   * @return acctSvcrRef
   */
  @Nonnull
  public String getAcctSvcrRef() {
    return acctSvcrRef;
  }

  public void setAcctSvcrRef(@Nonnull String acctSvcrRef) {
    this.acctSvcrRef = acctSvcrRef;
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndSts splmtryData(
      @Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
    return this;
  }

  /**
   * Get splmtryData
   * 
   * @return splmtryData
   */
  @Nullable
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData getSplmtryData() {
    return splmtryData;
  }

  public void setSplmtryData(@Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryData splmtryData) {
    this.splmtryData = splmtryData;
  }
}
