/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;







import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr {
  public static final String SERIALIZED_NAME_NM = "Nm";
 @JsonProperty(SERIALIZED_NAME_NM)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
   private String nm;

  public static final String SERIALIZED_NAME_ID = "Id";
 @JsonProperty(SERIALIZED_NAME_ID)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId id;

  public static final String SERIALIZED_NAME_CTCT_DTLS = "CtctDtls";
 @JsonProperty(SERIALIZED_NAME_CTCT_DTLS)
 @Nullable
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrCtctDtls ctctDtls;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr nm(@Nonnull String nm) {
    this.nm = nm;
    return this;
  }

  /**
   * Get nm
   * @return nm
   */
  @Nonnull
  public String getNm() {
    return nm;
  }

  public void setNm(@Nonnull String nm) {
    this.nm = nm;
  }


  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr id(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId getId() {
    return id;
  }

  public void setId(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrId id) {
    this.id = id;
  }


  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtr ctctDtls(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrCtctDtls ctctDtls) {
    this.ctctDtls = ctctDtls;
    return this;
  }

  /**
   * Get ctctDtls
   * @return ctctDtls
   */
 @Nullable
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrCtctDtls getCtctDtls() {
    return ctctDtls;
  }

  public void setCtctDtls(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfDbtrCtctDtls ctctDtls) {
    this.ctctDtls = ctctDtls;
  }


}

