/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId {
  public static final String SERIALIZED_NAME_OTHR = "Othr";
  @JsonProperty(SERIALIZED_NAME_OTHR)
  @Nullable
  private DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnIdOthr othr;

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnId othr(
      @Nullable DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnIdOthr othr) {
    this.othr = othr;
    return this;
  }

  /**
   * Get othr
   * 
   * @return othr
   */
  @Nullable
  public DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnIdOthr getOthr() {
    return othr;
  }

  public void setOthr(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfGrpHdrInstgAgtFinInstnIdOthr othr) {
    this.othr = othr;
  }
}
