/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.SimuladorCoreBank.model.debito;






import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;



/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrId
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrId {
  public static final String SERIALIZED_NAME_PRVT_ID = "PrvtId";
 @JsonProperty(SERIALIZED_NAME_PRVT_ID)
 @Nullable
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtId prvtId;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrId() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrId prvtId(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
    return this;
  }

  /**
   * Get prvtId
   * @return prvtId
   */
 @Nullable
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtId getPrvtId() {
    return prvtId;
  }

  public void setPrvtId(@Nullable DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfCdtrIdPrvtId prvtId) {
    this.prvtId = prvtId;
  }

}

