/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;

/**
 * DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp
 */

public class DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp {
  public static final String SERIALIZED_NAME_CNTS = "Cnts";
  @JsonProperty(SERIALIZED_NAME_CNTS)
  @Nullable
  private DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts;

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp() {
  }

  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlp cnts(
      @Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts) {
    this.cnts = cnts;
    return this;
  }

  /**
   * Get cnts
   * 
   * @return cnts
   */
  @Nullable
  public DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts getCnts() {
    return cnts;
  }

  public void setCnts(@Nullable DebitoResponseDocumentFIToFIDbtPmtStsRptTxInfAndStsSplmtryDataEnvlpCnts cnts) {
    this.cnts = cnts;
  }

}
