/*
 * Debito Core Banking | Servicio Pago Directo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.SimuladorCoreBank.model.debito;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nonnull;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

/**
 * DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData
 */

public class DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData {
  public static final String SERIALIZED_NAME_ENVLP = "Envlp";
  @JsonProperty(SERIALIZED_NAME_ENVLP)
  @Nonnull
  @NotNull(message = "REQUEST NO VALIDO, FALTAN CAMPOS MANDATORIOS")
  @Valid
  private DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlp envlp;

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData() {
  }

  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryData envlp(
      @Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
    return this;
  }

  /**
   * Get envlp
   * 
   * @return envlp
   */
  @Nonnull
  public DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlp getEnvlp() {
    return envlp;
  }

  public void setEnvlp(@Nonnull DebitoRequestDocumentFIToFICstmrDbtTrfCdtTrfTxInfSplmtryDataEnvlp envlp) {
    this.envlp = envlp;
  }
}
